### ISSUE TITLE
Feature request : Add currUser as targetDir

### ISSUE THREAD

**Issue by huexley** [Installomator/Installomator#1016]
Hello,

Many softwares like Chrome for example can be installed without user rights directly in a folder of the user's choice, like ~/Desktop or ~/Applications.

Is it possible to add these folders?

**Comment by acodega** [comment]
In order for Installomator to work, you'd then need to give PPPC allowances, and that's something we want to avoid as a prerequisite.

You should be able to accomplish similar behavior by making the current user the owner of the app in /Applications, which is actually the default behavior. [More info non the wiki](https://github.com/Installomator/Installomator/wiki/Configuration-and-Variables#owner-of-copied-apps).
