### ISSUE TITLE
Unable to install 1Password 8 on devices that have 1Password for Safari installed

### ISSUE THREAD

**Issue by cpressland** [Installomator/Installomator#1019]
When rebuilding a device from scratch sometimes VPP runs before Installomator, this results in `/Applications/1Password for Safari.app` being present on the device before our Jamf Policy for 1Password 8 runs. The 1Password 8 install then fails with the following log message:

`2023-04-30 10:14:09 : INFO  : 1password8 : App(s) found: /Applications/1Password for Safari.app`

**Comment by kstlouis** [comment]
`Not sure what you are expecting Installomator to do here`
Respectfully - I think it's pretty clear what Installomator should do here? `1Password for Safari` and `1Password 8` are two completely different apps, I don't think it's unreasonable to expect that it can install one despite the presence of the other.
