### ISSUE TITLE
Non printable characters when grepping AWS S3 headers

### ISSUE THREAD

**Issue by acodega** [Installomator/Installomator#1042]
While borrowing some Installomator code when writing a swiftDialog info box, I've discovered that AWS seems to return non printable characters when you grep a URL header. The non printable characters then interfere with Installomator's version comparison. Since it's common practice to use `cut -d"." -f1-3`, this doesn't happen on all labels that get `appNewVersion` from an AWS header. However I also noticed the use of `cut -d"." -f1-3` returns incomplete information for some labels, like perimeter81, which is version 9.0.0.28 not 9.0.0. Right now the AWS VPN Client label is returning 3.3.0, so the `cut` command is returning the non printable characters as well.

A quick and dirty test that shows the comparison issue:

```#!/bin/zsh

set -x

variable1="3.3.0"
downloadURL="https://d20adtppz83p9s.cloudfront.net/OSX/latest/AWS_VPN_Client.pkg"
variable2="$(curl -fsIL "${downloadURL}" | grep -i ^x-amz-meta-version | sed -E 's/x-amz-meta-version: //' | cut -d"." -f1-3)"

if [[ "$variable1" == "$variable2" ]]; then
  echo "YES"
else
  echo "NO"
fi
```

I wanted to post this as an Open issue if anyone knows why it's become common practice to use `cut -d"." -f1-3`? I think this would be a potential fix for any AWS S3 URLs:

`curl -fsIL "${downloadURL}" | grep -i ^x-amz-meta-version | sed -E 's/x-amz-meta-version: //' | tr -dc '[:print:]'`

For those who love to refactor stuff and use a less readable command, this could be used:

`curl -fsIL "$downloadURL" | awk -F ': ' '/^x-amz-meta-version/{gsub("\r",""); print $2}' | awk '{$1=$1;print}'`

**Comment by scriptingosx** [comment]
see also #915

**Comment by acodega** [comment]
Thanks. I had overlooked that. Closing this issue.
