### ISSUE TITLE
Tunnelblick is in a circle

### ISSUE THREAD

**Issue by bbrendon** [Installomator/Installomator#1082]
I'm running Installomator 10.4.
I had Tunnelblick 4.0 installed, then it updated to 3.8, now it wants to re-install 3.8 because I don't have 4.0 (log of that below).
Is github going crazy? Is there a bug in installomator?

```
2023-06-06 10:06:31 : INFO  : tunnelblick : App(s) found: /Applications/Tunnelblick.app
2023-06-06 10:06:31 : INFO  : tunnelblick : found app at /Applications/Tunnelblick.app, version 3.8.8b (build 5777), on versionKey CFBundleShortVersionString
2023-06-06 10:06:31 : INFO  : tunnelblick : appversion: 3.8.8b (build 5777)
2023-06-06 10:06:31 : INFO  : tunnelblick : Latest version of Tunnelblick is 4.0.0beta06 (build 5860)
2023-06-06 10:06:31 : REQ   : tunnelblick : Downloading https://github.com/Tunnelblick/Tunnelblick/releases/download/v3.8.8b/Tunnelblick_3.8.8b_build_5777.dmg to Tunnelblick.dmg
2023-06-06 10:06:34 : INFO  : tunnelblick : found blocking process Tunnelblick

```

**Comment by duderin0** [comment]
The label is set to download only what is released under the [Latest](https://github.com/Tunnelblick/Tunnelblick/releases/latest) tag, but the appNewVersion only checks the very top of the Releases page for the version number, which in this case is for a pre-release instead.

I think the intended behavior is to get the latest release and not the pre-release, so we'll have to change the AppNewVersion. Thankfully, /releases/latest can redirect to the proper page by adding -L to the curl. The sed command doesn't work for these vs. the pre-release version though, for some reason, but rather than work with that I'm switching things to xpath.

I've got a fix for you in an incoming pull request.

**Comment by bbrendon** [comment]
It used to download 4.0beta consistently. And according to some docs in Tunnelblick it is recommended for compatibility.( I know it’s strange. ). If it’s Downloading 3.8 now I think it’s going to be confusing for people.

**Comment by acodega** [comment]
The proper fix would be to change the downloadURL so not use downloadURLFromGit, since that will get the "latest" and not the pre-release. Tunnelblick is unusual in that they recommend running the latest beta version.

**Comment by duderin0** [comment]
Yeah that was what I was thinking, and had done for another label (bitwarden #1067). I spent some time trying to figure out a way to consistently get the beta, but Github doesn't have a /pre-release url redirect to always show the latest with that tag, only with release versions (again, like with Bitwarden). Theres probably another way but I don't have time to try working on this anymore.

**Comment by bbrendon** [comment]
I think I have a fix.  Could someone merge it if it passes?

```
version_plus_build=$(curl -sf https://github.com/Tunnelblick/Tunnelblick/releases  | grep -B2 'Pre-release' |grep -m 1 "/Tunnelblick/Tunnelblick/releases/tag/" | sed -r 's/.*Tunnelblick ([^<]+).*/\1/' | awk '{gsub(/ /,"_"); gsub(/\(|\)/,""); print}')
appNewVersion=$version_plus_build
version=$(echo $version_plus_build | awk -F_ '{print $1}')
downloadURL="https://github.com/Tunnelblick/Tunnelblick/releases/download/v${version}/Tunnelblick_${version_plus_build}.dmg"
```

**Comment by bbrendon** [comment]
@acodega I hate pinging people but can you provide some guidance to move this forward? Should I do a PR or can someone in the project kick this along?

**Comment by bbrendon** [comment]
This doesn't appear fixed.

The output of `curl -fsL "https://github.com/Tunnelblick/Tunnelblick/releases/latest" | xmllint --html --xpath 'substring-after(string(//h1[@class="d-inline mr-3"]), "Tunnelblick ")'  -`

Is

`3.8.8d (build 5779)`

**Comment by duderin0** [comment]
You might want to create your own PR

**Comment by bbrendon** [comment]
https://github.com/Installomator/Installomator/pull/1198
