### ISSUE TITLE
Lucid Link ID is incorrect

### ISSUE THREAD

**Issue by jasonflory** [Installomator/Installomator#1125]
Hi guys, the correct one is "3T5GSNBU6W". Ref: https://support.lucidlink.com/hc/en-us/articles/13948021944461-Deploying-LucidLink-with-Jamf-Pro-MDM

**Comment by duderin0** [comment]
According to the notes you linked:
`Important Note: The Lucid application has a different Team ID (Y4KMJPU2B4) to the Kernel Extension (3T5GSNBU6W). For the purposes of deployment and security around KEXTs, please use the Team ID (3T5GSNBU6W) for the KEXT approval.`

Running the LucidLink label through Installomator, it already gives what the documentation suggests the app should have, so I do not believe there is any issue. 

2023-07-10 14:03:47 : DEBUG : lucidlink : origin=Developer ID Installer: LucidLink Corp. (Y4KMJPU2B4)
2023-07-10 14:03:47 : INFO  : lucidlink : Team ID: Y4KMJPU2B4 (expected: Y4KMJPU2B4 )
