### ISSUE TITLE
Force MS Office updates

### ISSUE THREAD

**Issue by PhillyPhoto** [Installomator/Installomator#1156]
We use a 28 deferral config profile for Microsoft Office. The function to update Office however uses the MAU binary if it's found, and this causes an issue where it may see a newer version is available and tries to kick off the update, but that update will be out of scope because it's been less than 28 days since release. Can there be new tags added that don't utilize the MAU method if a newer version is detected? Something like "microsoftoffice365full" vs "microsoftoffice365"?

**Comment by acodega** [comment]
Installomator isn't meant for environments where you want to control what version is installed, like using deferrals.

I think it would be better to have a variable one can enable to not use the app label's `updateTool`. Having extra labels can add confusion and additional maintenance.
