### ISSUE TITLE
pgadmin4 download issue

### ISSUE THREAD

**Issue by deadly-muffin** [Installomator/Installomator#1170]
pgadmin4 Download Error:

WARN : pgadmin4 : No previous app found 2023-08-15 12:48:39 : WARN : pgadmin4 : could not find pgAdmin 4.app 2023-08-15 12:48:39 : INFO : pgadmin4 : appversion: 2023-08-15 12:48:39 : INFO : pgadmin4 : Latest version of pgAdmin 4 is 7.5 2023-08-15 12:48:39 : REQ : pgadmin4 : Downloading https://ftp.postgresql.org/pub/pgadmin/pgadmin4/v7.5/macos/pgadmin4-7.5.dmg to pgAdmin 4.dmg 2023-08-15 12:48:40 : ERROR : pgadmin4 : error downloading https://ftp.postgresql.org/pub/pgadmin/pgadmin4/v7.5/macos/pgadmin4-7.5.dmg ls: pgAdmin 4.dmg: No such file or directory 2023-08-15 12:48:40 : ERROR : pgadmin4 : File list: 2023-08-15 12:48:40 : ERROR : pgadmin4 : File type: pgAdmin 4.dmg: cannot open `pgAdmin 4.dmg' (No such file or directory) 2023-08-15 12:48:40 : INFO : pgadmin4 : App not closed, so no reopen. 2023-08-15 12:48:40 : ERROR : pgadmin4 : ERROR: Error downloading https://ftp.postgresql.org/pub/pgadmin/pgadmin4/v7.5/macos/pgadmin4-7.5.dmg error: * Trying 87.238.57.227:443... * Connected to ftp.postgresql.org (87.238.57.227) port 443 (#0) * ALPN: offers h2,http/1.1 * (304) (OUT), TLS handshake, Client hello (1): } [323 bytes data] * CAfile: /etc/ssl/cert.pem * CApath: none * (304) (IN), TLS handshake, Server hello (2): { [88 bytes data] * (304) (OUT), TLS handshake, Client hello (1): } [388 bytes data] * (304) (IN), TLS handshake, Server hello (2): { [187 bytes data] * (304) (IN), TLS handshake, Unknown (8): { [19 bytes data] * (304) (IN), TLS handshake, Certificate (11): { [4299 bytes data] * (304) (IN), TLS handshake, CERT verify (15): { [520 bytes data] * (304) (IN), TLS handshake, Finished (20): { [52 bytes data] * (304) (OUT), TLS handshake, Finished (20): } [52 bytes data] * SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384 * ALPN: server accepted h2 * Server certificate: * subject: CN=ftp.postgresql.org * start date: Jun 18 10:08:44 2023 GMT * expire date: Sep 16 10:08:43 2023 GMT * subjectAltName: host "ftp.postgresql.org" matched cert's "ftp.postgresql.org" * issuer: C=US; O=Let's Encrypt; CN=R3 * SSL certificate verify ok. * using HTTP/2 * h2 [:method: GET] * h2 [:scheme: https] * h2 [:authority: ftp.postgresql.org] * h2 [:path: /pub/pgadmin/pgadmin4/v7.5/macos/pgadmin4-7.5.dmg] * h2 [user-agent: curl/8.1.2] * h2 [accept: */*] * Using Stream ID: 1 (easy handle 0x12480b800) > GET /pub/pgadmin/pgadmin4/v7.5/macos/pgadmin4-7.5.dmg HTTP/2 > Host: ftp.postgresql.org > User-Agent: curl/8.1.2 > Accept: */* > < HTTP/2 404 < server: nginx < date: Tue, 15 Aug 2023 17:48:40 GMT < content-type: text/html; charset=UTF-8 < content-length: 146 * The requested URL returned error: 404 *

I think the URL for file has changed to:
https://ftp.postgresql.org/pub/pgadmin/pgadmin4/v7.5/macos/pgadmin4-7.5-x86_64.dmg

Thank you.

**Comment by duderin0** [comment]
There is a pending PR for this in #1084. Hopefully we'll get 10.5 out soon, but you can copy the code from there if you need in the meantime.
