### ISSUE TITLE
Update only - Skip if not found

### ISSUE THREAD

**Issue by tbcahill** [Installomator/Installomator#1176]
Is there a way to skip if app is not installed?
I would like to use installomator to install updates for installed apps only & skip any apps that are not already installed.

**Comment by duderin0** [comment]
You might want to look into [Patchomator](https://github.com/Mac-Nerd/patchomator) or [App-Auto-Patch](https://github.com/robjschroeder/App-Auto-Patch) that both utilize Installomator to update only installed apps. You can use them to either update everything found, update everything except whatever is in a list you create, or to only update ones from a list you provide.

**Comment by tbcahill** [comment]
Thank you1 I'll check them out.
