### ISSUE TITLE
RemoteDesktopManager Free & Enterprise Download - Error Code 2

### ISSUE THREAD

**Issue by it-vsg** [Installomator/Installomator#1177]
RemoteDesktopManager Error Code 2:

Executing Policy Remote Desktop Manager Enterprise
--
Running script Installomator 13.3...
Script exit code: 2
Script result: 2023-08-21 15:02:35 : REQ   :  : shifting arguments for Jamf2023-08-21 15:02:35 : REQ   : remotedesktopmanagerenterprise : ################## Start Installomator v. 10.3, date 2023-02-10 2023-08-21 15:02:35 : INFO  : remotedesktopmanagerenterprise : ################## Version: 10.3 2023-08-21 15:02:35 : INFO  : remotedesktopmanagerenterprise : ################## Date: 2023-02-10 2023-08-21 15:02:35 : INFO  : remotedesktopmanagerenterprise : ################## remotedesktopmanagerenterprise 2023-08-21 15:02:35 : INFO  : remotedesktopmanagerenterprise : SwiftDialog is not installed, clear cmd file var 2023-08-21 15:02:35 : INFO  : remotedesktopmanagerenterprise : BLOCKING_PROCESS_ACTION=tell_user 2023-08-21 15:02:35 : INFO  : remotedesktopmanagerenterprise : NOTIFY=success 2023-08-21 15:02:35 : INFO  : remotedesktopmanagerenterprise : LOGGING=INFO 2023-08-21 15:02:35 : INFO  : remotedesktopmanagerenterprise : LOGO=/Library/Application Support/JAMF/Jamf.app/Contents/Resources/AppIcon.icns 2023-08-21 15:02:35 : INFO  : remotedesktopmanagerenterprise : Label type: dmg 2023-08-21 15:02:35 : INFO  : remotedesktopmanagerenterprise : archiveName: Remote Desktop Manager.dmg 2023-08-21 15:02:35 : INFO  : remotedesktopmanagerenterprise : name: Remote Desktop Manager, appName: Remote Desktop Manager.app 2023-08-21 15:02:35.898 mdfind[8097:130457] [UserQueryParser] Loading keywords and predicates for locale "de_CH" 2023-08-21 15:02:35.898 mdfind[8097:130457] [UserQueryParser] Loading keywords and predicates for locale "de" 2023-08-21 15:02:35.929 mdfind[8097:130457] Couldn't determine the mapping between prefab keywords and predicates. 2023-08-21 15:02:35 : WARN  : remotedesktopmanagerenterprise : No previous app found 2023-08-21 15:02:35 : WARN  : remotedesktopmanagerenterprise : could not find Remote Desktop Manager.app 2023-08-21 15:02:35 : INFO  : remotedesktopmanagerenterprise : appversion:  2023-08-21 15:02:35 : INFO  : remotedesktopmanagerenterprise : Latest version not specified. 2023-08-21 15:02:35 : REQ   : remotedesktopmanagerenterprise : Downloading  to Remote Desktop Manager.dmg 2023-08-21 15:02:35 : ERROR : remotedesktopmanagerenterprise : error downloading  ls: Remote Desktop Manager.dmg: No such file or directory 2023-08-21 15:02:35 : ERROR : remotedesktopmanagerenterprise : File list:  2023-08-21 15:02:35 : ERROR : remotedesktopmanagerenterprise : File type: Remote Desktop Manager.dmg: cannot open `Remote Desktop Manager.dmg' (No such file or directory) 2023-08-21 15:02:35 : INFO  : remotedesktopmanagerenterprise : App not closed, so no reopen. 2023-08-21 15:02:35 : ERROR : remotedesktopmanagerenterprise : ERROR: Error downloading  error: * URL rejected: No host part in the URL * Closing connection -1 curl: (3) URL rejected: No host part in the URL  2023-08-21 15:02:35 : REQ   : remotedesktopmanagerenterprise : ################## End Installomator, exit code 2

**Comment by acodega** [comment]
Believe fixed in Installomator 10.6
