### ISSUE TITLE
Wireshark appNewVersion URL needs to change

### ISSUE THREAD

**Issue by gabemarcelino** [Installomator/Installomator#1195]
Looks like Wireshark change the XML in there sparkle: https://www.wireshark.org/update/0/Wireshark/4.0.0/macOS/x86-64/en-US/stable.xml and the download link doesn't have latest version anymore I created the fix:
```
wireshark)
    name="Wireshark"
    type="dmg"
    appNewVersion=$(curl -fs "https://www.wireshark.org/update/0/Wireshark/4.0.0/macOS/x86-64/en-US/stable.xml" | xmllint --xpath '//item/title/text()' - | awk '{print $2}')
    if [[ $(arch) == i386 ]]; then
      downloadURL="https://2.na.dl.wireshark.org/osx/Wireshark%20$appNewVersion%20Intel%2064.dmg"
    elif [[ $(arch) == arm64 ]]; then
      downloadURL="https://2.na.dl.wireshark.org/osx/Wireshark%20$appNewVersion%20Arm%2064.dmg"
    fi
    expectedTeamID="7Z6EMTD2C6"
    ;;
```

**Comment by asri-tm** [comment]
Which version of installomator you had issues with?
10.5beta seems to run and install fine on my machine.

#1034

**Comment by gabemarcelino** [comment]
I tried 10.4 and 11 Beta, I am not seeing 10.5 beta on the release list. it installs fine but does not detect the appNewVersion variable looks like it gets the full download link instead of the app version and results to a reinstall:
` : INFO  : wireshark : Latest version of Wireshark is https://2.na.dl.wireshark.org/osx/Wireshark%204.0.8%20Intel%2064.dmg`

**Comment by asri-tm** [comment]
> I tried 10.4 and 11 Beta, I am not seeing 10.5 beta on the release list. it installs fine but does not detect the appNewVersion variable looks like it gets the full download link instead of the app version and results to a reinstall: ` : INFO : wireshark : Latest version of Wireshark is https://2.na.dl.wireshark.org/osx/Wireshark%204.0.8%20Intel%2064.dmg`

You can find 10.5beta on the [main branch](https://github.com/Installomator/Installomator/blob/main/Installomator.sh)

**Comment by asri-tm** [comment]
ah i see it, so $appNewVersion needs updating. happy to raise a PR for the fix but a little held up with other duties at the moment.
Will get on it no one has actioned this

**Comment by bra1ncramp** [comment]
This should improve the results:
```
wireshark)
    name="Wireshark"
    type="dmg"
    appNewVersion=$(curl -fs "https://www.wireshark.org/update/0/Wireshark/4.0.0/macOS/x86-64/en-US/stable.xml" | xpath -e '//rss/channel/item/enclosure/@sparkle:version' 2>/dev/null | cut -d '"' -f 2)
    urlToParse=$(curl -fs "https://www.wireshark.org/update/0/Wireshark/4.0.0/macOS/x86-64/en-US/stable.xml" | xmllint --xpath '/rss/channel/item/enclosure/@url' - | head -1 | cut -d ':' -f 2 | cut -d '%' -f 1)
    if [[ $(arch) == i386 ]]; then
      downloadURL="https:$urlToParse%20$appNewVersion%20Intel%2064.dmg"
    elif [[ $(arch) == arm64 ]]; then
      downloadURL="https:$urlToParse%20$appNewVersion%20Arm%2064.dmg"
    fi
    expectedTeamID="7Z6EMTD2C6"
    ;;
```
see https://github.com/Installomator/Installomator/pull/1370
and 
https://github.com/Installomator/Installomator/issues/1242
