### ISSUE TITLE
buildLabel.sh tweaks

### ISSUE THREAD

**Issue by PhillyPhoto** [Installomator/Installomator#1196]
I noticed with the buildLabel.sh script that line 5 is misconfigured. Instead of:

`downloadURL=${"https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-arm64.pkg"}`

at minimum is should be:

`downloadURL="https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-arm64.pkg"`

to hard code the URL, but ideally:

`downloadURL="$1"`

to pass the URL to the script properly.

Also, to avoid errors with basename, line 153 should be changed from:

`echo $(basename $downloadURL)`

to:

`echo $(basename "$downloadURL")`

**Comment by scriptingosx** [comment]
> Also, to avoid errors with basename, line 153 should be changed from:
> 
> ```
> echo $(basename $downloadURL)
> ```
> 
> to:
> 
> ```
> echo $(basename "$downloadURL")
> ```

This is a **zsh** script. You don't need to double quote every substitution in zsh.

**Comment by scriptingosx** [comment]
You need to create a PR, reverting a commit that far down the tree is not advisable.
