### ISSUE TITLE
Whitespace and newline barriers to contributing

### ISSUE THREAD

**Issue by pythoninthegrass** [Installomator/Installomator#124]
First, thank you @scriptingosx et al for creating Installomator. I'm really looking forward to moving away from AutoPkg.

With that said, I'm not exaggerating when I say that I spent literal _hours_ trying to figure out how to use `.gitattributes`, as well as VSCode `settings.json` exclusions and extension troubleshooting to ignore whitespace and the missing newline at the end-of-file (EOF.)

After much gnashing of the teeth, I gave up and saved without formatting and re-committed an as-is copy of `Installomator.sh`.

My proposal is to strip trailing/stray whitespace and add a newline at EOF on the main branch and ask contributors to do the same for their respective code blocks.

<img width="1183" alt="Screen Shot 2021-01-21 at 2 59 08 PM" src="https://user-images.githubusercontent.com/4097471/105411691-53739480-5bf9-11eb-933a-4e807818b24e.png">

**Comment by acodega** [comment]
Please excuse the late response. Is there a chance we could talk on MacAdmins.org Slack about this? I am EST time.
