### ISSUE TITLE
not downloading current version VLC

### ISSUE THREAD

**Issue by sdkemm** [Installomator/Installomator#1267]
I've updated installomator to current version. When checking the Jamf computer policy logs, I noticed in the logs Installomater reports 'No newer version (line 50) but when I go out to the venders site there is a new version. What am I missing?

<h1 translate="DETAILS" translate-values="{}" class="ng-scope">Details</h1>

			<jamf-dismiss-button class="jamf-dismiss-button ng-scope ng-isolate-scope" ng-if="$ctrl.showDismiss" on-dismiss="$ctrl.close()"><jamf-button size="small" icon="close" on-click="$ctrl.dismiss(event)" custom-classes="dismiss" class="ng-isolate-scope">
	
		
		
        
	

</jamf-button>
</jamf-dismiss-button><div class="modal-header ng-scope" ng-transclude="header" ng-if="$ctrl.showHeader">
		</div>

        <div class="modal-body" ng-transclude="body" ng-class="{'no-footer': !$ctrl.showFooter}"><div class="history-details">

Executing Policy Enterprise wide - VLC - update
--
Running script Installomator v10.5...
Script exit code: 0
Script result: 2023-10-19 09:18:22 : REQ   :  : shifting arguments for Jamf2023-10-19 09:18:22 : REQ   : vlc : ################## Start Installomator v. 10.5, date 2023-10-15 2023-10-19 09:18:22 : INFO  : vlc : ################## Version: 10.5 2023-10-19 09:18:22 : INFO  : vlc : ################## Date: 2023-10-15 2023-10-19 09:18:22 : INFO  : vlc : ################## vlc 2023-10-19 09:18:22 : DEBUG : vlc : DEBUG mode 1 enabled. 2023-10-19 09:18:22 : INFO  : vlc : SwiftDialog is not installed, clear cmd file var 2023-10-19 09:18:22 : INFO  : vlc : setting variable from argument DEBUG=0 2023-10-19 09:18:22 : DEBUG : vlc : name=VLC 2023-10-19 09:18:23 : DEBUG : vlc : appName= 2023-10-19 09:18:23 : DEBUG : vlc : type=dmg 2023-10-19 09:18:23 : DEBUG : vlc : archiveName= 2023-10-19 09:18:23 : DEBUG : vlc : downloadURL=http://get.videolan.org/vlc/3.0.18/macosx/vlc-3.0.18-arm64.dmg 2023-10-19 09:18:23 : DEBUG : vlc : curlOptions= 2023-10-19 09:18:23 : DEBUG : vlc : appNewVersion=3.0.18 2023-10-19 09:18:23 : DEBUG : vlc : appCustomVersion function: Not defined 2023-10-19 09:18:23 : DEBUG : vlc : versionKey=CFBundleShortVersionString 2023-10-19 09:18:23 : DEBUG : vlc : packageID= 2023-10-19 09:18:23 : DEBUG : vlc : pkgName= 2023-10-19 09:18:23 : DEBUG : vlc : choiceChangesXML= 2023-10-19 09:18:23 : DEBUG : vlc : expectedTeamID=75GAHG3SZQ 2023-10-19 09:18:23 : DEBUG : vlc : blockingProcesses= 2023-10-19 09:18:23 : DEBUG : vlc : installerTool= 2023-10-19 09:18:23 : DEBUG : vlc : CLIInstaller= 2023-10-19 09:18:23 : DEBUG : vlc : CLIArguments= 2023-10-19 09:18:23 : DEBUG : vlc : updateTool= 2023-10-19 09:18:23 : DEBUG : vlc : updateToolArguments= 2023-10-19 09:18:23 : DEBUG : vlc : updateToolRunAsCurrentUser= 2023-10-19 09:18:23 : INFO  : vlc : BLOCKING_PROCESS_ACTION=tell_user 2023-10-19 09:18:23 : INFO  : vlc : NOTIFY=success 2023-10-19 09:18:23 : INFO  : vlc : LOGGING=DEBUG 2023-10-19 09:18:23 : INFO  : vlc : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns 2023-10-19 09:18:23 : INFO  : vlc : Label type: dmg 2023-10-19 09:18:23 : INFO  : vlc : archiveName: VLC.dmg 2023-10-19 09:18:23 : INFO  : vlc : no blocking processes defined, using VLC as default 2023-10-19 09:18:23 : DEBUG : vlc : Changing directory to /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.EQ5PB0GK 2023-10-19 09:18:23 : INFO  : vlc : App(s) found: /Applications/VLC.app 2023-10-19 09:18:23 : INFO  : vlc : found app at /Applications/VLC.app, version 3.0.18, on versionKey CFBundleShortVersionString 2023-10-19 09:18:23 : INFO  : vlc : appversion: 3.0.18 2023-10-19 09:18:23 : INFO  : vlc : Latest version of VLC is 3.0.18 2023-10-19 09:18:23 : INFO  : vlc : There is no newer version available. 2023-10-19 09:18:23 : DEBUG : vlc : Deleting /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.EQ5PB0GK 2023-10-19 09:18:23 : DEBUG : vlc : Debugging enabled, Deleting tmpDir output was: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.EQ5PB0GK 2023-10-19 09:18:23 : INFO  : vlc : Installomator did not close any apps, so no need to reopen any apps. 2023-10-19 09:18:23 : REQ   : vlc : No newer version. 2023-10-19 09:18:23 : REQ   : vlc : ################## End Installomator, exit code 0
Running Recon...
Retrieving inventory preferences from https://ewscripps.jamfcloud.com/...
Locating accounts...
Searching path: /System/Applications
Locating package receipts...
Locating software updates...
Locating plugins...
Locating printers...
Searching path: /Applications
Locating hardware information (macOS 13.6.0)...

</div></div>

**Comment by greatkemo** [comment]
New fix in PR #1347

**Comment by sjurlohne** [comment]
It's not working for 3.0.21. The $latestVersionURL points to "https://get.videolan.org/vlc/last/macosx/", but the "last" folder does not point to the latest version, rather to 3.0.20. Changing the URL to "https://get.videolan.org/vlc/3.0.21/macosx/" will work, but is no solution.
If we can't trust the "last" folder, perhaps it's possible to list all folders under "https://get.videolan.org/vlc/", sort the list so the highest nubmer is at the top/bottom, and pull the latest version form that? I don't know....

**Comment by uurazzle** [comment]
Hi:

Here is a working updated label that fixes the issue.

`vlc)
	# VLC is a versatile, open-source multimedia player that supports a wide range of audio, video, and streaming formats across multiple platforms
    name="VLC"
    type="dmg"
    appNewVersion=$(curl -s https://www.videolan.org/vlc/#download | xmllint --html --xpath "//script[contains(text(),'var PLATFORMS')]" - 2>/dev/null | grep -o '"osx":{"name":"macOS[^}]*' | grep -o '"latestVersion":"[^"]*' | sed 's/"latestVersion":"//')
    downloadURL="https://get.videolan.org/vlc/$appNewVersion/macosx/vlc-$appNewVersion-universal.dmg"
    expectedTeamID="75GAHG3SZQ"
    ;;`

**Comment by timnottom** [comment]
Thanks @uurazzle, that works like a charm here. Could you create a pull request for this?

**Comment by uurazzle** [comment]
HI @timnottom:

Ok, created an alternative method pull request for VLC that is less forgettable by the VLC maintainers.

https://github.com/Installomator/Installomator/pull/1719
