### ISSUE TITLE
label `microsoftteamsnew` appNewVersion command errors

### ISSUE THREAD

**Issue by bartreardon** [Installomator/Installomator#1271]
The following doesn't return a version string. When separating the components, `xpath` is issuing usage instructions indicating incorrect arguments

https://github.com/Installomator/Installomator/blob/0e3080e3408d89fe373fa6703e57f1eb2b7b6fe4/fragments/labels/microsoftteamsnew.sh#L8C21-L8C191

the following should work:

```bash
curl -fs https://macadmins.software/latest.xml | xmllint --xpath '/latest/package[id="com.microsoft.teams2.standalone"]/version/text()' - | awk '{print $1}'
```

**Comment by Theile** [comment]
Actually, Installomator do get the version in that line. The thing is that Installomator add `-e` to `path` as it is a function in Installomator.

So the line will be: `curl -fs https://macadmins.software/latest.xml | xpath -e '//latest/package[id="com.microsoft.teams2.standalone"]/version' 2>/dev/null | sed -E 's/<version>([0-9.]*) .*/\1/'`

Returning:
`23272.2708.2452.9689`

**Comment by bartreardon** [comment]
Ah cool - either or 🙂 (I'm used to `xmllint --xpath` so easier for me to troubleshoot).

does xpath have the concept of `/text()` to return the tag value rather than use `sed` to strip it out? Doesn't really matter I guess if it works but just curious.

**Comment by Theile** [comment]
We have a comment in the code to make the switch, but I think we found out it would break some labels, and would not work out. I know certain functions exist, but not certain how to add it, in a a line like this:
`curl -fs "https://update.mactracker.ca/appcast-b.xml" | xpath -q -e '//rss/channel/item[last()]/enclosure/@url' `

**Comment by Theile** [comment]
I found it:
`curl -fs "https://update.mactracker.ca/appcast-b.xml" | xpath -q -e 'string(//rss/channel/item[last()]/enclosure/@url)'`

I know it is `string()` but the descriptions I find, mentions that `text()` is a search tool.

Is that different in `xmllint`?
