### ISSUE TITLE
firefoxesr Version Detection Issue

### ISSUE THREAD

**Issue by reuven-cohen** [Installomator/Installomator#1295]
https://product-details.mozilla.org/1.0/firefox_versions.json shows the firefox_esr version as 115.4.0esr
The info.plist of the installed firefoxesr now shows version as 115.4.0 (sans esr suffix)

May need to amend the version detection to take this into consideration as any auto-update workflows will now run everytime.

**Comment by AWestermeyer** [comment]
I have the same issue: Firefox ESR auto-updating all the time !

Actually, `curl -fs "https://product-details.mozilla.org/1.0/firefox_versions.json"` command to retrieve Firefox version returns:

```json
{
    "FIREFOX_AURORA": "",
    "FIREFOX_DEVEDITION": "129.0b5",
    "FIREFOX_ESR": "115.13.0esr",
    "FIREFOX_ESR_NEXT": "128.0esr",
    "FIREFOX_NIGHTLY": "130.0a1",
    "LAST_MERGE_DATE": "2024-07-08",
    "LAST_RELEASE_DATE": "2024-07-09",
    "LAST_SOFTFREEZE_DATE": "2024-07-04",
    "LAST_STRINGFREEZE_DATE": "2024-07-05",
    "LATEST_FIREFOX_DEVEL_VERSION": "129.0b5",
    "LATEST_FIREFOX_OLDER_VERSION": "3.6.28",
    "LATEST_FIREFOX_RELEASED_DEVEL_VERSION": "129.0b5",
    "LATEST_FIREFOX_VERSION": "128.0",
    "NEXT_MERGE_DATE": "2024-08-05",
    "NEXT_RELEASE_DATE": "2024-08-06",
    "NEXT_SOFTFREEZE_DATE": "2024-08-01",
    "NEXT_STRINGFREEZE_DATE": "2024-08-02"
}
```

Versions for Firefox ESR are suffixed with “esr”, **115.13.0esr** for example, whereas versions located in the application's plist file do not contain this suffix!

To retrieve the version number that corresponds to that of the application, we need to add a line to the script (see below) that determines ESR version, triming the tailing esr:

```bash
firefoxVersions=$(curl -fs "https://product-details.mozilla.org/1.0/firefox_versions.json")
appNewVersion=$(getJSONValue "$firefoxVersions" "FIREFOX_ESR")
appNewVersion=${appNewVersion//"esr"/} # add this line ->  trims the string "esr" form app version
```

**Comment by acodega** [comment]
Please discuss on #951 , as that issue is older and both seem to be discussing the same issue.
