### ISSUE TITLE
The label for ClickShare is not working

### ISSUE THREAD

**Issue by sjurlohne** [Installomator/Installomator#1326]
The label for ClickShare is not working. They've changed the download link, so a unique link is created for every download.
Found this info from HomeBrew, where they had to remove ClickShare because of this.

https://github.com/Homebrew/homebrew-cask/issues/147460

**Comment by TacoDienstag** [comment]
Yess, hopefully Barco isn't motivated enough to change this again...

**Comment by kevinVodi** [comment]
Can confirm as of today (3-15-24) all is well with the ClickShare label and this can likely be marked resolved.

**Comment by acodega** [comment]
Fixed in 10.6
