### ISSUE TITLE
ProtonVPN: URL for dmg cannot be extracted anymore

### ISSUE THREAD

**Issue by eumelkind** [Installomator/Installomator#1334]
ProtonVPN: URL for dmg cannot be extracted anymore.
The current download URL is https://protonvpn.com/download/ProtonVPN_mac_v4.0.0.dmg, but that is not listed in the HTML under https://protonvpn.com/download

**Comment by guy-tallon** [comment]
There is a PR here https://github.com/Installomator/Installomator/pull/1283

**Comment by acodega** [comment]
Believe fixed in Installomator 10.6
