### ISSUE TITLE
OBS file name format changed 

### ISSUE THREAD

**Issue by MatimusPrime** [Installomator/Installomator#1335]
The following lines need to be changed to compensate. 
 
line 5831 and 5833 and be archiveName="obs-studio-[0-9.]*-macOS-Apple.dmg" and archiveName="obs-studio-[0-9.]*-macOS-Intel.dmg"

tested in our environment and its working now with this change. 

thanks adamcodega for the fix.

**Comment by k0nker** [comment]
That didn't work because of their changing of caps, and it didn't catch the exta .0.0 etc. This did:

`    if [[ $(arch) == "arm64" ]]; then
        archiveName="OBS-Studio-[0-9.]*-macOS-Apple.dmg"
    elif [[ $(arch) == "i386" ]]; then
        archiveName="OBS-Studio-[0-9.]*-macOS-Intel.dmg"
    fi`

**Comment by acodega** [comment]
Believe fixed in Installomator 10.6
