### ISSUE TITLE
Blender error -ERROR : blender : need to provide 'downloadURL'

### ISSUE THREAD

**Issue by sbryant82** [Installomator/Installomator#1342]
Label -Blender

The Blender application is failing to install and provides the following error:ERROR : blender : need to provide 'downloadURL'

Executing Policy (testing) New Installomater copy
Running script Installomator 10.5...
Script exit code: 1
Script result: 2023-11-21 05:40:10 : REQ   :  : shifting arguments for Jamf
2023-11-21 05:40:10 : REQ   : blender : ################## Start Installomator v. 10.5, date 2023-10-15
2023-11-21 05:41:26 : ERROR : blender : need to provide 'downloadURL'

**Comment by greatkemo** [comment]
This is fixed in PR #1343

**Comment by sbryant82** [comment]
I believe the issue actually came from:https://www.blender.org/news/cyberattack-november-2023/

**Comment by greatkemo** [comment]
@sbryant82 That is highly probable.  Thanks for sharing.

**Comment by acodega** [comment]
Fixed in 10.6
