### ISSUE TITLE
Virtualbox is downloading from japanese site

### ISSUE THREAD

**Issue by timnottom** [Installomator/Installomator#1345]
The VirtualBox label/fragment now downloads from the Japanese URL and is returning an old version: 7.0.10, while the URL without a country specified is giving the latest version 7.0.12.

We could change the url from:
https://www.oracle.com/jp/virtualization/technologies/vm/downloads/virtualbox-downloads.html
to
https://www.oracle.com/virtualization/technologies/vm/downloads/virtualbox-downloads.html

**Comment by timnottom** [comment]
See:
https://github.com/Installomator/Installomator/pull/1346/commits/4475c294428a8a6258f6a347ff14f2ae0996c13c

**Comment by acodega** [comment]
Believe fixed in Installomator 10.6
