### ISSUE TITLE
Vagrant downloadURL changed

### ISSUE THREAD

**Issue by hooleahn** [Installomator/Installomator#1349]
Based off https://github.com/Installomator/Installomator/issues/817

The download url of vagrant has changed from https://developer.hashicorp.com/vagrant/downloads to https://developer.hashicorp.com/vagrant/install

The browser redirects to the new URL but installomator does not.

suggestion for new label

```
vagrant)
    name="Vagrant"
    type="pkgInDmg"
    pkgName="vagrant.pkg"
    downloadURL=$(curl -fs "https://developer.hashicorp.com/vagrant/install" | tr '"' '\n' | grep "^https.*\.dmg$" | head -1)
    appNewVersion=$( echo $downloadURL | cut -d "/" -f5 )
    expectedTeamID="D38WU7D763"
    ;;
```

**Comment by acodega** [comment]
Believe fixed in Installomator 10.6
