### ISSUE TITLE
ClickShare downloading windows version

### ISSUE THREAD

**Issue by JMEngineeringMacOS** [Installomator/Installomator#1352]
Hi, attempting to use installomator to update the ClickShare app. It seems to be downloading the windows version of the application as seen below, please let me know if you have any queries. Thankyou!
--
Running script Installomator.sh v10.5..
Script exit code: 22
Script result: 2023-11-28 11:26:46 : REQ   :  : shifting arguments for Jamf2023-11-28 11:26:46 : REQ   : clickshare : ################## Start Installomator v. 10.4, date 2023-06-02 2023-11-28 11:26:46 : INFO  : clickshare : ################## Version: 10.4 2023-11-28 11:26:46 : INFO  : clickshare : ################## Date: 2023-06-02 2023-11-28 11:26:46 : INFO  : clickshare : ################## clickshare (eval):1: no such file or directory: https://www.barco.com 2023-11-28 11:26:47 : INFO  : clickshare : BLOCKING_PROCESS_ACTION=tell_user 2023-11-28 11:26:47 : INFO  : clickshare : NOTIFY=success 2023-11-28 11:26:47 : INFO  : clickshare : LOGGING=INFO 2023-11-28 11:26:47 : INFO  : clickshare : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns 2023-11-28 11:26:47 : INFO  : clickshare : Label type: appInDmgInZip 2023-11-28 11:26:47 : INFO  : clickshare : archiveName: ClickShare.zip 2023-11-28 11:26:47 : INFO  : clickshare : no blocking processes defined, using ClickShare as default 2023-11-28 11:26:47 : INFO  : clickshare : App(s) found: /Applications/ClickShare.app 2023-11-28 11:26:47 : INFO  : clickshare : found app at /Applications/ClickShare.app, version 4.33.0-b8, on versionKey CFBundleShortVersionString 2023-11-28 11:26:47 : INFO  : clickshare : appversion: 4.33.0-b8 2023-11-28 11:26:47 : INFO  : clickshare : Latest version of ClickShare is 0.0.0-b0 2023-11-28 11:26:47 : REQ   : clickshare : Downloading https://www.barco.com to ClickShare.zip 2023-11-28 11:26:48 : REQ   : clickshare : no more blocking processes, continue with update 2023-11-28 11:26:48 : REQ   : clickshare : Installing ClickShare 2023-11-28 11:26:48 : INFO  : clickshare : Unzipping ClickShare.zip tar: Error opening archive: Unrecognized archive format 2023-11-28 11:26:48 : INFO  : clickshare : App not closed, so no reopen. 2023-11-28 11:26:48 : ERROR : clickshare : ERROR: couldn't find dmg in zip ClickShare.zip 2023-11-28 11:26:48 : REQ   : clickshare : ################## End Installomator, exit code 22
Error running script: return code was 22.
Running command /usr/local/Installomator/Installomator.sh clickshare...
Result of command:2023-11-28 11:26:48 : REQ   : clickshare : ################## Start Installomator v. 10.5, date 2023-10-15 2023-11-28 11:26:48 : INFO  : clickshare : ################## Version: 10.5 2023-11-28 11:26:48 : INFO  : clickshare : ################## Date: 2023-10-15 2023-11-28 11:26:48 : INFO  : clickshare : ################## clickshare (eval):1: no such file or directory: https://www.barco.com 2023-11-28 11:26:49 : INFO  : clickshare : BLOCKING_PROCESS_ACTION=tell_user 2023-11-28 11:26:49 : INFO  : clickshare : NOTIFY=success 2023-11-28 11:26:49 : INFO  : clickshare : LOGGING=INFO 2023-11-28 11:26:49 : INFO  : clickshare : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns 2023-11-28 11:26:49 : INFO  : clickshare : Label type: appInDmgInZip 2023-11-28 11:26:49 : INFO  : clickshare : archiveName: ClickShare.zip 2023-11-28 11:26:49 : INFO  : clickshare : no blocking processes defined, using ClickShare as default 2023-11-28 11:26:49 : INFO  : clickshare : App(s) found: /Applications/ClickShare.app 2023-11-28 11:26:49 : INFO  : clickshare : found app at /Applications/ClickShare.app, version 4.33.0-b8, on versionKey CFBundleShortVersionString 2023-11-28 11:26:49 : INFO  : clickshare : appversion: 4.33.0-b8 2023-11-28 11:26:49 : INFO  : clickshare : Latest version of ClickShare is 0.0.0-b0 2023-11-28 11:26:49 : REQ   : clickshare : Downloading https://www.barco.com to ClickShare.zip 2023-11-28 11:26:50 : REQ   : clickshare : no more blocking processes, continue with update 2023-11-28 11:26:50 : REQ   : clickshare : Installing ClickShare 2023-11-28 11:26:50 : INFO  : clickshare : Unzipping ClickShare.zip tar: Error opening archive: Unrecognized archive format 2023-11-28 11:26:50 : INFO  : clickshare : Installomator did not close any apps, so no need to reopen any apps. 2023-11-28 11:26:50 : ERROR : clickshare : ERROR: couldn't find dmg in zip ClickShare.zip 2023-11-28 11:26:50 : REQ   : clickshare : ################## End Installomator, exit code 22
Running Recon...

**Comment by TacoDienstag** [comment]
Fixed in PR #1308, did you tried this one?

**Comment by acodega** [comment]
Fixed in 10.6
