### ISSUE TITLE
Aspera Connect download identifier changed

### ISSUE THREAD

**Issue by meysq** [Installomator/Installomator#1415]
Hey all, noticed Aspera was no longer installing via Installomator. Turns out that IBM changed how they label Aspera on their fixes website (_macOS vs the full _macOS_x86_64 in the download link) and it was pulling the last version before the change, which is no longer active.

Suggestion for new Aspera module:

`asperaconnect)
    name="$(curl -fS 'https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm~Other%20software&product=ibm/Other+software/IBM+Aspera+Connect' --data-raw 'showStatus=false' | egrep -o "ibm-aspera-connect_[0-9.]+_macOS" | head -n1)"
    type="pkg"
    downloadURL="https://d3gcli72yxqn2z.cloudfront.net/downloads/connect/latest/bin/${name}_x86_64.pkg"
    appNewVersion=$(echo "${name}" | sed -E 's/.*_([0-9.]*)_mac.*/\1/')
    expectedTeamID="RJ747GSBCT"
    ;;`

**Comment by JJSS1111** [comment]
This worked for us - thanks

**Comment by kryptonit1** [comment]
There's apparently an Apple Silicon version available as well, which does not seem to be hosted on Cloudfront.

**Comment by kryptonit1** [comment]
I created a PR for this since there was none. I also made som changes to the new suggested label.

**Comment by acodega** [comment]
Fixed in release 10.6
