### ISSUE TITLE
Request application - LogiOptions+

### ISSUE THREAD

**Issue by scr-malu** [Installomator/Installomator#1448]
Could you please add about a Logitech application called **Logi Options+**, an older generation application called Logi Options was registered. 

https://www.logitech.com/en-us/setup/mxsetup/logi-options.html

**Comment by moojomoore** [comment]
Hey @scr-malu - Is this what you're looking for? It can be found under `logitechoptionsplus` 

[Logitech Options Plus Fragment](https://github.com/Installomator/Installomator/blob/0e3080e3408d89fe373fa6703e57f1eb2b7b6fe4/fragments/labels/logitechoptionsplus.sh)

**Comment by scr-malu** [comment]
@moojomoore I thought I had looked for it, but I couldn’t find it. Thank you!
