### ISSUE TITLE
Microsoft Edge label is using MAU

### ISSUE THREAD

**Issue by sjurlohne** [Installomator/Installomator#1484]
MAU has been deprecated for Microsoft Edge for a while, but the label is still using the updateTool.
Edge is using the EdgeUpdater tool now, and I don't think it can be run manually using scripts.

https://learn.microsoft.com/en-us/deployedge/edge-learnmore-edgeupdater-for-macos

**Comment by acodega** [comment]
Believe fixed in Installomator 10.6
