### ISSUE TITLE
Suggestion: IGNORE_UPDATETOOL=true/false to override any updateTools in labels.

### ISSUE THREAD

**Issue by sjurlohne** [Installomator/Installomator#1485]
Why?
Because some updateTools sometimes fail. Using INSTALL=force is currently the only way to override, and this will trigger a full install no matter what version, while IGNORE_UPDATETOOL=true should just use the built in Installomator behaviour and update the app if a newer version is found.

**Comment by Maarten-Wijnants** [comment]
This pull request implements that functionality: https://github.com/Installomator/Installomator/pull/899

**Comment by Theile** [comment]
We can already send `updateTool=""` when calling Installomator and the it will be ignored. So closing this issue.
