### ISSUE TITLE
Aleph One has change the name of Marathon

### ISSUE THREAD

**Issue by nickkoval** [Installomator/Installomator#1495]
The app name on the volume has changed from "Marathon.app" to "Classic Marathon.app". This name change by Aleph One prevents Marathon from being copied to the Applications folder once the .dmg has been mounted.

**Comment by nickkoval** [comment]
After doing some testing, this can be resolved by adding the line
`appName="Classic Marathon.app"`
into the marathon case select statement.

**Comment by acodega** [comment]
Believe fixed in Installomator 10.6
