### ISSUE TITLE
Aleph One has changed the name of Marathon 2

### ISSUE THREAD

**Issue by nickkoval** [Installomator/Installomator#1496]
The app name on the volume has changed from "Marathon 2.app" to "Classic Marathon 2.app". This name change by Aleph One prevents Marathon 2 from being copied to the Applications folder once the .dmg has been mounted.

**Comment by nickkoval** [comment]
After doing some testing, this can be resolved by adding the line
`appName="Classic Marathon 2.app"`
into the marathon case select statement.

**Comment by acodega** [comment]
Believe fixed in Installomator 10.6
