### ISSUE TITLE
Aleph One has changed the name of Marathon Infinity

### ISSUE THREAD

**Issue by nickkoval** [Installomator/Installomator#1497]
The app name on the volume has changed from "Marathon Infinity.app" to "Classic Marathon Infinity.app". This name change by Aleph One prevents Marathon Infinity from being copied to the Applications folder once the .dmg has been mounted.

**Comment by nickkoval** [comment]
After doing some testing, this can be resolved by adding the line
`appName="Classic Marathon Infinity.app"`
into the `marathoninfinity` case select statement.

**Comment by acodega** [comment]
Believe fixed in Installomator 10.6
