### ISSUE TITLE
Miro download URL is changed

### ISSUE THREAD

**Issue by meshyamsundar** [Installomator/Installomator#1509]
Hi Team,

the URL for downloading Miro is changed  

Old URL : https://desktop.miro.com/platforms/darwin-arm64/Miro.dmg

Updated URL : https://desktop.miro.com/platforms/darwin-arm64/Install-Miro.dmg

Please update the same.

**Comment by nvanjaarsveld** [comment]
Additionally, the Intel URL's, if used:
Intel (new): https://desktop.miro.com/platforms/darwin/Install-Miro.dmg
Intel (old): https://desktop.miro.com/platforms/darwin/Miro.dmg

**Comment by acodega** [comment]
Believe fixed in Installomator 10.6
