### ISSUE TITLE
appNewVersion missing for Microsoft Office Business Pro?

### ISSUE THREAD

**Issue by damacguy** [Installomator/Installomator#153]
Maybe I'm missing something (**_VERY LIKELY)_**, but it looks like there's no appNewVersion for Office Biz Pro?

Shouldn't something like this go between lines 2905 & 2906 (or there abouts)...
`appNewVersion=$( curl -fsIL "https://go.microsoft.com/fwlink/?linkid=2009112" | grep -i location: | grep -o "/Microsoft_.*pkg" | cut -d "_" -f 3 )`

**Comment by acodega** [comment]
Yep, that would work (It's better to use $downloadURL rather than manually specifying the URL. Would you like to submit a pull request with the updated label?

**Comment by acodega** [comment]
Did you want to submit a PR for this issue?

**Comment by Theile** [comment]
I have added appNewVersion to this, like the other Microsoft titles (from the file name downloaded).
