### ISSUE TITLE
jamfconnect appNewVersion variable not present

### ISSUE THREAD

**Issue by karsondude97** [Installomator/Installomator#1545]
Jamf Connect installs each time no matter the version since there is no appNewVersion variable for Jamf Connect.

**Comment by karsondude97** [comment]
`jamfconnect)
    name="Jamf Connect"
    type="pkgInDmg"
    packageID="com.jamf.connect"
    appNewVersion=$(getJSONValue "$(curl -s "https://learn-be.jamf.com/api/bundlelist?name_filter.field=name&name_filter.value=jamf-connect-documentation-current")" ".bundle_list[0].title" | awk -F ' ' '{print $NF}')
    downloadURL="https://files.jamfconnect.com/JamfConnect.dmg"
    expectedTeamID="483DWKW443"
    ;;`

**Comment by scriptingosx** [comment]
#1546

**Comment by acodega** [comment]
Believe fixed in Installomator 10.6
