### ISSUE TITLE
VMWare Horizon Client installing very old version

### ISSUE THREAD

**Issue by Simply-Guy** [Installomator/Installomator#157]
The current script installs a very old version v 2006.x while today we're at v 2103.

**Comment by ShitttyScripts** [comment]
Now the vmware horizon install just fails saying the URL is out of date.
And this 0.7.0b1 version, the vmwarehorizonclient tag and a few others were partially written over

**Comment by Theile** [comment]
VMWare has totally screwed their web page, so curl cannot get any content, no matter if I also try using different user-agents. I think we have to remove this label.
You are very welcome to get back if other labels are "partially written over", thank you.

**Comment by ShitttyScripts** [comment]
Darn, too bad about VMware.
For the ones that I thought was partially written over, i must have been seeing things or it was only skype. I noticed it the other day and didn't leave my comment right away. Thanks for the speedy replies!
