### ISSUE TITLE
Sourcetree downloading old version

### ISSUE THREAD

**Issue by PhantomPhixer** [Installomator/Installomator#159]
The sourcetree sparkle feed has 4.02 as the latest version but the manual download is 4.1.

**Comment by acodega** [comment]
Which version of Installomator are you running? (Which version and from which branch, dev or master)

**Comment by midni9ht** [comment]
Hey @PhantomPhixer
PR #188 should fix this issue by using a more recent feed.

**Comment by Theile** [comment]
This is fixed.
