### ISSUE TITLE
QGIS not installing

### ISSUE THREAD

**Issue by peterlbk** [Installomator/Installomator#1602]
All seems to work fine, except at the end we see that installomator does not install QGIS:

ERROR : qgis-pr : ERROR: Error verifying /Volumes/QGIS.app/QGIS.app error:
/Volumes/QGIS.app/QGIS.app: rejected (invalid destination for symbolic link in bundle)

**Comment by scriptingosx** [comment]
when you download the app manually and run `spctl -a -vvv /Volumes/QGIS.app/QGIS.app` do you get the same error?

**Comment by scriptingosx** [comment]
so the good news is: it is not an Installomator problem.

The Gatekeeper verification of the app is failing and Installomator is rejecting it because of that. You will have to get in touch with the vendor to fix their signing and notarization.
