### ISSUE TITLE
Slack Github App

### ISSUE THREAD

**Issue by gueetch** [Installomator/Installomator#1655]
Hello,

would you mind adding the Slack Github App to the Installomator Org so anyone can register for releases update on Slack ?
This is an official Github App

Repo: https://github.com/integrations/slack
More info: https://slack.github.com/
Github App: https://github.com/apps/slack (use this link to add it to your org, require org owner permission).

Why we need you to install it on your org for us to be able to have notifications on our slack: https://github.com/integrations/slack/issues/454#issuecomment-373038982

Thanks !

**Comment by acodega** [comment]
This isn't an app that's installed on your Mac, it gets installed in your Slack instance. There are instructions on the repo link you provided.

**Comment by acodega** [comment]
We'd recommend using the RSS feed instead, as was mentioned in your link from GitHub.
