### ISSUE TITLE
Microsoft Autoupdate not updating Office Pro

### ISSUE THREAD

**Issue by damacguy** [Installomator/Installomator#175]
Found this odd - probably more of a problem with AutoUpdate than Installomator?

Been seeing that MS Office Pro Business hasn't been updating all week and just got time to investigate. The log file shows an error running AutoUpdate...
> 2021-05-20 20:09:42  shifting arguments for Jamf
> 2021-05-20 20:09:42 microsoftofficebusinesspro ################## Start Installomator v. 0.5.0
> 2021-05-20 20:09:42 microsoftofficebusinesspro ################## microsoftofficebusinesspro
> 2021-05-20 20:09:42 microsoftofficebusinesspro BLOCKING_PROCESS_ACTION=prompt_user
> 2021-05-20 20:09:42 microsoftofficebusinesspro NOTIFY=silent
> 2021-05-20 20:09:42 microsoftofficebusinesspro LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
> 2021-05-20 20:09:42 microsoftofficebusinesspro Changing directory to /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.y2C1bjEk
> 2021-05-20 20:09:42 microsoftofficebusinesspro found app at /Applications/Microsoft PowerPoint.app, version 16.48
> 2021-05-20 20:09:42 microsoftofficebusinesspro appversion: 16.48
> 2021-05-20 20:09:42 microsoftofficebusinesspro appversion & updateTool
> 2021-05-20 20:09:42 microsoftofficebusinesspro Function called: runUpdateTool
> 2021-05-20 20:09:42 microsoftofficebusinesspro running /Library/Application Support/Microsoft/MAU2.0/Microsoft AutoUpdate.app/Contents/MacOS/msupdate --install

>**2021-05-20 20:11:43 microsoftofficebusinesspro ERROR: Error running /Library/Application Support/Microsoft/MAU2.0/Microsoft AutoUpdate.app/Contents/MacOS/msupdate**

> 2021-05-20 20:11:43 microsoftofficebusinesspro Deleting /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.y2C1bjEk
> 2021-05-20 20:11:43 microsoftofficebusinesspro App not closed, so no reopen.
> 2021-05-20 20:11:43 microsoftofficebusinesspro ################## End Installomator, exit code 15 

...so I did it manually and got this...
> sudo /Library/Application\ Support/Microsoft/MAU2.0/Microsoft\ AutoUpdate.app/Contents/MacOS/msupdate --install
> Detecting and downloading updates...
> Cannot determine Update Assistant state.
> Update Assistant is available.
> Update Assistant is available.
> Update Assistant is available.
> Update Assistant is available.
> Update Assistant is available.
> Update Assistant is available.
> Update Assistant is available.
> Update Assistant is available.
> Update Assistant is available.
> Update Assistant is available.
> Update Assistant is available.
> No result returned from Update Assistant

I know there's an update, so I ran `msupdate --list` and got the list of expected updates.
> sudo /Library/Application\ Support/Microsoft/MAU2.0/Microsoft\ AutoUpdate.app/Contents/MacOS/msupdate --list   
> Checking for updates...
> Update Assistant is available.
> Updates available:
>   XCEL2019  Excel Update 16.49.0 (21050901)
>   ONMC2019  OneNote Update 16.49.0 (21050901)
>   OPIM2019  Outlook Update 16.49.0 (21050901)
>   MSWD2019  Word Update 16.49.0 (21050901)
>   PPT32019  PowerPoint Update 16.49.0 (21050901)

Tried Installomator again and it worked.

Maybe have installomator run --list and output the results to null and then run the update?

**Comment by Theile** [comment]
We are apparently not super at giving quick support at this team, but have you tried to do this later? How did that go?

If I remember correctly there has been som problems with Microsoft AutoUpdate and versioning, that we do not have anything to do with. So not really sure this fault is on Installomator.
