### ISSUE TITLE
Ultimaker Cura isn't detecting Intel Macs during installation.

### ISSUE THREAD

**Issue by ksalters55** [Installomator/Installomator#1786]
I installed Ultimaker Cura on two Intel Macs and installomator installed the ARM version.

**Comment by acodega** [comment]
Is this repeatable? Architecture detection is very straightforward, but we've heard murmurings of this with a few other labels. If it's repeatable, try running Installomator with DEBUG logging enabled and post the log using a Code block.

**Comment by ksalters55** [comment]
I attempted the installation on multiple Intel Macs with the same results. Attached is the installomator log.
<img width="1098" alt="UltimakerCura installation log" src="https://github.com/user-attachments/assets/23135a27-e3a2-4437-b3f7-09e32ab62cd6">

**Comment by acodega** [comment]
I found the issue, the version you're using has the old label, before architecture support was added. I noticed that Installomator is setting `archiveName="Ultimaker_Cura-[0-9].*-mac.dmg"` which is the old archiveName.

It should be one of these two. `UltiMaker-Cura-[0-9.]*-macos-ARM64.dmg` or `UltiMaker-Cura-[0-9.]*-macos-X64.dmg`. Architecture support was added about eight months ago in #1385 but unfortunately I think it was only merged in March, and was added to the 10.6 release version this week. You should be good to go with the new release.
