### ISSUE TITLE
Microsoft Remote Help app Label

### ISSUE THREAD

**Issue by r-kamstra** [Installomator/Installomator#1789]
Can someone make a label for the "Microsoft Remote Help" app?

**Comment by marceldekuiper** [comment]
I made one (my first) but due to time off and work, didn't do anything with it yet. 
https://github.com/Installomator/Installomator/compare/main...marceldekuiper:Installomator:main

Since this is the first time for me, was kindoff afraid to make a PR etc.

**Comment by r-kamstra** [comment]
Thanks! @marceldekuiper, though in the meanwhile  I solved this with a script in my onboarding workflow.
