### ISSUE TITLE
xpath is missing expression flag

### ISSUE THREAD

**Issue by ian-atkinson** [Installomator/Installomator#1795]
Hi,

There are quite a lot of calls within the script to xpath with no arguments (113 of them I think) and these fail as xpath needs calling with -e before the expression

```
sh-3.2# appNewVersion=$(curl -fs https://macadmins.software/latest.xml | xpath '//latest/package[id="com.microsoft.teams2.standalone"]/version' 2>/dev/null | sed -E 's/<version>([0-9.]*) .*/\1/')
sh-3.2# echo $appNewVersion

sh-3.2# appNewVersion=$(curl -fs https://macadmins.software/latest.xml | xpath -e '//latest/package[id="com.microsoft.teams2.standalone"]/version' 2>/dev/null | sed -E 's/<version>([0-9.]*) .*/\1/')
sh-3.2# echo $appNewVersion
23306.3408.2576.5406
sh-3.2#
```

xpath does not take a call without this argument (at least on Sonoma)

```
sh-3.2# curl -fs https://macadmins.software/latest.xml | xpath '//latest/package[id="com.microsoft.teams2.standalone"]/version'
Usage:
/usr/bin/xpath5.34 [options] -e query [-e query...] [filename...]

If no filenames are given, supply XML on STDIN. You must provide at
least one query. Each supplementary query is done in order, the
previous query giving the context of the next one.

Options:

-q quiet, only output the resulting PATH.
-s suffix, use suffix instead of linefeed.
-p postfix, use prefix instead of nothing.
-n Don't use an external DTD.
sh-3.2#
```

trying on an older machine this looks to work fine so I think the command line args have changed at some point:

```
BW-WKSDIGPR-10:~ admin$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G9323
BW-WKSDIGPR-10:~ admin$ curl -fs https://macadmins.software/latest.xml | xpath '//latest/package[id="com.microsoft.teams2.standalone"]/version'
Found 1 nodes:
-- NODE --
<version>23306.3408.2576.5406 [231213] 64-bit</version>
BW-WKSDIGPR-10:~ admin$
```

Adding -e on this older system then causes the command to fail:

```
BW-WKSDIGPR-10:~ admin$ curl -fs https://macadmins.software/latest.xml | xpath -e '//latest/package[id="com.microsoft.teams2.standalone"]/version'
Cannot open file '-e' at /System/Library/Perl/Extras/5.18/XML/XPath.pm line 53.
```

This is an issue as it makes the script quite unportable without writing a function to check the MacOS version and then calling an appropriately formatted command? Piping straight into xpath wouldn't work universally either way I don't think.

**Comment by scriptingosx** [comment]
You'd think we'd have encountered something that was changed in Big Sur already. And in fact we have, because, well, Installomator does not error on macOS later than Big Sur.

Since we needed to deal with this in a way that maintained compatibility with older versions of macOS (Installomator still runs macOS 10.14+) we overloaded the `path` command with a custom function that calls the proper invocation of `xpath` depending on which version of macOS it runs on: 

https://github.com/Installomator/Installomator/blob/82001300b2ecb055bc08276bccc59925578e1548/fragments/functions.sh#L208
