### ISSUE TITLE
Broken app label: obs

### ISSUE THREAD

**Issue by timnottom** [Installomator/Installomator#1806]
**What's wrong with the app label?**
The app label's downloadURL is coming up blank
I checked version 10.6 with our version and I noticed that the downloadURL was changed for obs. A fix is mentioned here https://github.com/Installomator/Installomator/pull/1344 but is not giving any results when I use it. The fix mentioned here: https://github.com/Installomator/Installomator/pull/1581 (which is from a later date) does return the good results. 

**Installomator version**
What version are you running? (Ex: Installomator v. 10.7beta, date 2024-08-31)
10.6

**Additional context**
Could it be that the 2 pull requests mentioned above were mixed up?

**Installomator log**
**At the bottom of this report**, provide a log, either by running Installomator in Terminal and saving the output, or by downloading the result log from your MDM. [Debug logging level](https://github.com/Installomator/Installomator/wiki/Configuration-and-Variables#logging-level) is not needed for easily identified issues, like a `downloadURL` is blank or an `appNewVersion` is incorrect. *PLEASE format the log [using a code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks)!*

When running:
```
name="OBS"
type="dmg"
if [[ $(arch) == "arm64" ]]; then
	SUFeedURL="https://obsproject.com/osx_update/updates_arm64_v2.xml"
elif [[ $(arch) == "i386" ]]; then
	SUFeedURL="https://obsproject.com/osx_update/updates_x86_64_v2.xml"
fi
appNewVersion=$(curl -fs "$SUFeedURL" | xpath '(//rss/channel/item[sparkle:channel="stable"]/sparkle:shortVersionString/text())[1]' 2>/dev/null)
downloadURL=$(curl -fs "$SUFeedURL" | xpath 'string(//rss/channel/item[sparkle:channel="stable"]/enclosure/@url[1])' 2>/dev/null)
archiveName=$(basename "$downloadURL")   
versionKey="CFBundleShortVersionString"
blockingProcesses=( "OBS Studio" )
expectedTeamID="2MMRE5MTB8"
```
`$appNewVersion` returns blank

When running:
```
name="OBS"
type="dmg"
if [[ $(arch) == "arm64" ]]; then
	archiveName="obs-studio-[0-9.]*-macos-Apple.dmg"
elif [[ $(arch) == "i386" ]]; then
	archiveName="obs-studio-[0-9.]*-macos-Intel.dmg"
fi
downloadURL=$(downloadURLFromGit obsproject obs-studio )
appNewVersion=$(versionFromGit obsproject obs-studio )
expectedTeamID="2MMRE5MTB8"
```
`$appNewVersion` returns: 30.2.3 (which is the latest version)

**Comment by acodega** [comment]
You can't copy and paste a variable into Terminal to see it's value if the variable is using `xpath`. It's a valid command but Installomator is actually running `xpath -e ...`. Copy and pasting the variable as-is will cause it to appear blank.

When the label is run, Installomator determines this URL as the downloadURL: `https://cdn-fastly.obsproject.com/downloads/obs-studio-30.2.3-macos-apple.dmg`

And `appNewVersion`: `30.2.3`

If Installomator is failing, you'll need to review the log of the Installomator run itself.

**Comment by timnottom** [comment]
Hi @acodega, running the label with `xpath -e` is indeed giving back the right result, mea culpa. I did not know that this was different when running the script in its entirety. I always copy and paste the complete label in CodeRunner (plus a shebang) and the functions used in the label, and then do an `echo $appNewVersion` and a `echo $downloadURL` to see the results. I will probably need to be testing it with the complete script in the feature. Thanks for the feedback!

**Comment by gilburns** [comment]
@timnottom There's a function in the full script that determines the xpath behavior based on the OS version. When something in the script uses xpath the function is called. Then the binary with the appropriate argument is called by the function.


# Handling of differences in xpath between Catalina and Big Sur
xpath() {
	# the xpath tool changes in Big Sur and now requires the `-e` option
	if [[ $(sw_vers -buildVersion) > "20A" ]]; then
		/usr/bin/xpath -e $@
		# alternative: switch to xmllint (which is not perl)
		#xmllint --xpath $@ -
	else
		/usr/bin/xpath $@
	fi
}

**Comment by timnottom** [comment]
Thanks @gilburns, I must have missed that one!
