### ISSUE TITLE
Remove contribution credits from app labels

### ISSUE THREAD

**Issue by acodega** [Installomator/Installomator#184]
Frequently, app labels will include code comments giving credit to the person who made the app label. I appreciate wanting to give credit, but it makes the app labels harder to grep when you're looking for an app label. (ie, try searching `Slack`)

I'd advocate that we remove any existing code comments and not add them going forward.

The best way to get credit for an app is to submit a pull request. I plan on writing a blog post on how to do this soon.

**Comment by isaacatmann** [comment]
100% agree, we credit should either be in a separate file that is linked once at the top, in the GitHub commits or (other).  Currently the code has a LOT of comments in it.
