### ISSUE TITLE
Broken app labels: MIcrosoft reset labels

### ISSUE THREAD

**Issue by acodega** [Installomator/Installomator#1901]
**What's wrong with the app label?**
office-reset.com is now offline. All reset labels for Microsoft apps need to be depreceated.

**Installomator version**
N/A

**Additional context**
MIcrosoft took office-reset.com offline a few weeks ago.

**Installomator log**
N/A

**Comment by PC-SPEZIALIST** [comment]
[office-reset.com](https://office-reset.com/) is working fine here.
