### ISSUE TITLE
Figma installs but needs to be moved out of and then back into the Applications folder

### ISSUE THREAD

**Issue by darklink87** [Installomator/Installomator#196]
Figma downloads and installs as expected, but is only a stub installer that checks to see if it's located in the Applications folder. Even though it is, it asks to be moved elsewhere, and then back in to the Applications folder. If users are not Administrators, they are unable to do this, and the app is unusable.

**Comment by acodega** [comment]
This was discussed in #autopkg on the MacAdmins.org Slack a little while ago. The URL to download a ZIP of the full app is `https://desktop.figma.com/mac/Figma.zip`. Feel free to open a PR on the label, or one of us will get to it I'm sure.

**Comment by acodega** [comment]
Are you interested in submitting a PR for this?

**Comment by darklink87** [comment]
> Are you interested in submitting a PR for this?

Yup! Finally got around to rebuilding my local fork and just put in a PR. #205

**Comment by darklink87** [comment]
My PR was accepted a few weeks ago and the issue was resolved, so this can be closed.
