### ISSUE TITLE
VLC download URL does not work

### ISSUE THREAD

**Issue by darklink87** [Installomator/Installomator#199]
Using "curl -fs http://update.videolan.org/vlc/sparkle/vlc-intel64.xml" shows that it's 2 versions behind the latest build, so there appears to be a delay in it getting updated. Running the full command of "curl -fs http://update.videolan.org/vlc/sparkle/vlc-intel64.xml | xpath '//rss/channel/item[last()]/enclosure/@url' 2>/dev/null | cut -d '"' -f 2" returns nothing, which is also a bit odd as well.

**Comment by adibue** [comment]
It looks like there is a problem with sparkle feeds in general. The VLC app updater shows 3.0.14 as the latest version, where the website indicates 3.0.16 being the latest one.
I just found out that the same behaviour exists for the Brave Browser, where the sparkle feed does not show the most recent version either.
I'll try to find out where to report those issues.

**Comment by adibue** [comment]
Here we go: https://code.videolan.org/videolan/vlc/-/issues/25861

**Comment by adibue** [comment]
@darklink87 According to the reply I got from a VLC dev, this is expected behaviour. The sparkle feed will be updated next week.

**Comment by adibue** [comment]
The sparkle feeds have been updated now.

**Comment by darklink87** [comment]
This can technically be marked as "fixed" for now, but it's going to happen again whenever there's another version update. 

Does anyone know if it's possible to tap into the same feed that Jamf uses to track VLC versions? They seem to have expanded their catalog greatly over the last few months, and they're fast to update whenever there's a new release.

**Comment by Theile** [comment]
I think that in regards to Installomator this IS fixed. We cannot handle not-updated web sites. 
If there is a temporary software title or version you need to install, there is also the valuesfromarguments label where things can be set manually for these rare cases.

**Comment by Theile** [comment]
Bad sparkle feed
