### ISSUE TITLE
Zoom Client for Meetings app - download link update

### ISSUE THREAD

**Issue by appleluka** [Installomator/Installomator#209]
Please update links to download Zoom Client for Meetings app (not IT version) to download x86 or ARM version of the app. 

https://zoom.us/download # #

**Comment by adibue** [comment]
What do you exactly want to achieve with that? As far as I can tell, the package for IT Admins behaves exactly the same, as long as no special configurations are set. Plus it automatically installs the correct zoom app for the underlying architecture.
So I guess, changing the `downloadURL`s would make the label more complex without having any benefit.

Or do I miss something?

**Comment by appleluka** [comment]
you're right! the IT package is actually Universal build! Thank you! Didn't know that!

**Comment by adibue** [comment]
Glad I could help :-)
