### ISSUE TITLE
Support GitHub API token

### ISSUE THREAD

**Issue by kenchan0130** [Installomator/Installomator#23]
When we use devices in an organization, we use the same IP to access various websites.
Since the GitHub API has rate limits on the same IP, API calls in our organization that do not use a token may be trapped by the rate limit.

And when we implement CI, we still have the same problem.

That's why I think it would be good to support API calls with tokens.

Related to https://github.com/scriptingosx/Installomator/pull/4#issuecomment-633017326.

**Comment by acodega** [comment]
Closing old issue. (Excuse the lateness, doing some housekeeping on Issues)
