### ISSUE TITLE
[request] add Jetbrains Toolbox

### ISSUE THREAD

**Issue by akashima** [Installomator/Installomator#230]
I want to add Jetbrains toolbox.
Jetbrains toolbox is Jetbrains products install and update management app.

I hear from my company member must that I install PHPStrom from Jetrains toolbox.
Certainly I also felt that it was better to manage the Jetbrains app from the management app.

```
jetbrainstoolbox)
    name="JetBrains Toolbox"
    type="dmg"
    downloadURL="https://download.jetbrains.com/product?code=TB&latest&distribution=mac"
    appNewVersion=$(curl -fs "https://data.services.jetbrains.com/products/releases?code=TB&latest=true&type=release" | grep -o 'version*.*,' | cut -d '"' -f3)
    expectedTeamID="2ZEFAR8TH3"
    ;;
```

**Comment by Theile** [comment]
Take a look at this PR: https://github.com/Installomator/Installomator/pull/231

I have updated them all, and included Toolbox (also with M1 version).
