### ISSUE TITLE
Please consider using absolute paths to binaries in script instead of only binary names

### ISSUE THREAD

**Issue by fredjohnsen** [Installomator/Installomator#237]
I believe this would make the script more secure & I would be happy to create a pull request to submit a version of the script or scripts with this modification. Thanks.

**Comment by fredjohnsen** [comment]
Writing that email probably took more effort than it would to convert to absolute paths. 

I don't really want to argue, but, here are several reasons:

1) Absolute paths are unambiguous. 

Variable expansion errors are often difficult to trace. The fewer instances of expansion a script has the less likely it is to contain errors.

2) Absolute paths are safe.

The article I sent covers this better than I can & you agreed with it.

3) Absolute paths make your script more portable.

i.e., if you know the OS you are deploying your script on is x.y.z, you know what's in it. Calling absolute paths is a form of validation like tab completion - validating the path as you type it.

If someone has heavily modified their user environment with shell profiles, aliases & $PATH variables of their own your script with $PATH might not work as expected. It would, though, if you just called everything from where it actually is.

4) URLs are file paths.

Web designers use absolute paths to resources for the same reasons: avoiding redirection, avoiding nefarious crawling / scraping, safety.

**Comment by Theile** [comment]
As long as we have a defined the PATH variable, and we only use commands from SIP protected folders we are not going to change this behavior as it will only make the script bigger, and not more secure. 

We use our spare time on this for the benefit of the community and if someone note or ask about specific stuff we are eager to explain the situation, for this person to learn more, just like we are eager to learn more. Thats why you got a lengthy reply that might have taken longer to write, but it is also why Armin shows up around the world to talk about scripting for macOS, and why I'm personally in this. 

You don't have to repeat your same points again, we understand how we fulfill these points already.
