### ISSUE TITLE
Splashtop SOS Installer

### ISSUE THREAD

**Issue by ryantgrimes** [Installomator/Installomator#239]
splashtopsos)
    name="Splashtop SOS"
    type="dmg"
    if [[ $(arch) != "i386" ]]; then
        printlog "Architecture: arm64 (not i386)"
        downloadURL="https://download.splashtop.com/sos/SplashtopSOS.dmg"
        appNewVersion=$(curl -s https://omahaproxy.appspot.com/history | awk -F',' '/mac_arm64,stable/{print $3; exit}')
    else
        printlog "Architecture: i386"
        downloadURL="https://download.splashtop.com/sos/SplashtopSOS.dmg"
        appNewVersion=$(curl -s https://omahaproxy.appspot.com/history | awk -F',' '/mac,stable/{print $3; exit}')
    fi
    expectedTeamID="CPQQ3AW49Y"
    ;;

**Comment by Theile** [comment]
Can you provide more information, as I also wrote on Slack?
Something wrong with different versions but same download on architecture, and versions differ from what the download actually is.

**Comment by Theile** [comment]
I have added this in our latest 0.7beta.
