### ISSUE TITLE
Brave label on the wrong line

### ISSUE THREAD

**Issue by jnichols35** [Installomator/Installomator#241]
https://github.com/Installomator/Installomator/blob/ca17fa3c6b5d619af2ed441fad037d831e5ea1e3/Installomator.sh#L1232

just wanted to point out that the brave label is on the wrong line

**Comment by Theile** [comment]
I don't know what you saw or if things fell i to the right place by themselves, but I don't see the problem. At least not in our updated 0.7beta.
