### ISSUE TITLE
Docker no longer installing

### ISSUE THREAD

**Issue by trevoedwards** [Installomator/Installomator#244]
All of the links in the script are erroring out for me. Looks like Docker recently restructured its offerings and you're no longer able to grab the installer without an account. 

This one should probably be removed from the script, unfortunately.

**Comment by acodega** [comment]
Do you have a log or terminal output as an example? At first glance the URLs still work in my browser. I'll perform an actual Installomator run later tonight.

**Comment by trevoedwards** [comment]
Looks like I may have jumped the gun on this one. Not running into the 'access denied' errors I was getting yesterday when hitting the download URL's and I was able to install via Installomator this morning.
