### ISSUE TITLE
Display App-Icon in Dialog

### ISSUE THREAD

**Issue by Apfelpom** [Installomator/Installomator#251]
Let the App-Icon be shown instead of the distribution logos: f.e. we use a script derived from Installomator.sh to push settings and use:

`button=$(DisplayDialog "$AppToDealWith braucht neue Voreinstellungen und muss kurz beendet werden. Jetzt?" "Gerne" "Zähneknirsch" "Gerne" "$AppToDealWith bitte schließen" "/Applications/Rocket.Chat.app/Contents/Resources/Rocket.Chat.icns" 300)`

So Installomator.sh could target the .icns logo of each application to show it in the Dialog.

![Display App-Icon in Dialog](https://user-images.githubusercontent.com/3330707/132752312-ba173acd-f229-4112-b8ad-ec10a6d269d7.png)

**Comment by Theile** [comment]
We have chosen to show the MDM logo or the App Store logo as predefined logos in the solution. But you can send a path to any file you want. 

Many developers use different names for their icns files, so there is really no way we could automate any of this. If you want the path as in your example, you can send that to the `LOGO` variable. 

I close this, as we cannot do anything about it, but please write back, if you think I have misunderstood.
