### ISSUE TITLE
VMWare Horizon

### ISSUE THREAD

**Issue by damacguy** [Installomator/Installomator#261]
The curl command or downloadURL and appNewVersion both return "301 Moved Permanently", but the URL used in both still appears to be current...
[https://customerconnect.vmware.com/en/downloads/details?downloadGroup=CART22FQ2_MAC_2106.1&productId=1027&rPId=74409](https://customerconnect.vmware.com/en/downloads/details?downloadGroup=CART22FQ2_MAC_2106.1&productId=1027&rPId=74409)

No idea what the problem might be.

**Comment by Theile** [comment]
You can change `curl -fs` to `curl -fsL` and then you will get these results for `downloadURL` and `appNewVersion`:
```
https://download3.vmware.com/software/view/viewclients/CART21FQ2/VMware-Horizon-Client-2006-8.0.0-16531451.dmg
8.0.0
```
I have corrected this for the next release. Please let me know if this is the right version and all.

**Comment by damacguy** [comment]
Oh perfect! YAY! Thanks.
