### ISSUE TITLE
Feature Request: Add Zoom.gov

### ISSUE THREAD

**Issue by kylejericson** [Installomator/Installomator#269]
Here is a curl link for this can you add this to your script

curl -L https://www.zoomgov.com/client/latest/ZoomInstallerIT.pkg -o /tmp/ZoomInstallerIT.pkg

Thanks

**Comment by acodega** [comment]
Would you like to make a pull request for this? Bonus points if you're able to work out appNewVersion too! You can model off of the [zoom label](https://github.com/Installomator/Installomator/blob/dev/fragments/labels/zoom.sh).

Fork the dev branch with a label like `kylejericson-zoomgov,` make a new label in the [fragments/labels](https://github.com/Installomator/Installomator/tree/dev/fragments/labels) folder, and then open a pull request.

Thanks!
