### ISSUE TITLE
cleanupAndExit with trap

### ISSUE THREAD

**Issue by kenchan0130** [Installomator/Installomator#272]
While running the Installomator script, the process may be interrupted for some reason.
For example, the case where the "Self Service" of Jamf policy is canceled by an end-user while it is running.

In that case, the dmg mount and so on may continue to remain, so it would be good if `cleanupAndExit` can be executed even if the process is stopped.

The method doesn't have to use `trap`, but in a shell script, this kind of function has been originally achieved by `trap`.

**Comment by acodega** [comment]
Do either of you want to open a PR to add this support? You would want to do it against the `dev` branch, which we use for new non label related features.

**Comment by acodega** [comment]
Closing no response.
