### ISSUE TITLE
VSCodium doesn't download

### ISSUE THREAD

**Issue by mtbhuskies** [Installomator/Installomator#296]
Script is trying to download the dmg and the dmg.sha1

Adding  `&& ! /sha1/`  to the end of the curl command fixes the issue.

`downloadURL=$(curl -fs "https://api.github.com/repos/VSCodium/vscodium/releases/latest" | awk -F '"' "/browser_download_url/ && /dmg/ && ! /sig/ && ! /CLI/ && ! /sha256/ && ! /sha1/ { print \$4 }")`

**Comment by acodega** [comment]
This is fixed in version 9, the current dev branch. The label was updated to use Installomator's native GitHub support. Could you test and confirm?

**Comment by mtbhuskies** [comment]
@acodega Thanks. I can confirm this is fixed in version 9. Much appreciation.
