### ISSUE TITLE
Utilzing JAMF params for script variables

### ISSUE THREAD

**Issue by erishiamu** [Installomator/Installomator#313]
This is a suggestion/question not an issue so feel free to close if that is out of scope. 

Is there a technical reason that variables such as BLOCKING_PROCESS_ACTION, NOTIFY, and REOPEN are hardcoded vs being written to accept JAMF policy input? I understand this is somewhat genericized to fit other MDMs, but these values could easily change on a per-app or even per-policy basis. 

Its not too hard to 'fix' this but it would be nice to not have to re-apply customization when updating the JAMF script. mediocre example:

```
if [ -n $5 ]; then 
NOTIFY=$5
else
NOTIFY=success
fi
```

**Comment by scriptingosx** [comment]
This already works, though probably slightly differently than you would expect:

https://github.com/installomator/installomator#configuration-from-arguments

just add the variable assignments as extra arguments

```
./Installomator.sh desktoppr DEBUG=0 NOTIFY=silent
```

In the Jamf policy interface just add the variable assignments in the extra argument fields, the order does not matter.

There are multiple reasons we are doing it this way:

- Installomator is built to not only work with Jamf Pro, but other management systems as well. we have to be very flexible in how we deal with arguments.
- when you use fixed positional arguments, but you want leave at their default, the syntax of the call becomes very awkward
- Jamf Pro "only" allows for eight configurable arguments, a limit which Installomator has easily reached and surpassed.

**Comment by scriptingosx** [comment]
<img width="795" alt="Screen Shot 2021-11-10 at 16 22 04" src="https://user-images.githubusercontent.com/1933192/141141579-779e38b3-f15a-4335-b873-70b27389e6e7.png">
