### ISSUE TITLE
Microsoft Edge for enterprise renamed to business? 

### ISSUE THREAD

**Issue by motionbug** [Installomator/Installomator#327]
microsoftedgeenterprisestable doesn't work 

The URL seems to have changed or Microsoft has renamed it to Microsoft Edge for Business..

URL within script -> https://go.microsoft.com/fwlink/?linkid=2093438 

New page for Edge when googling Edge Enterprise 

https://www.microsoft.com/en-us/edge/business/download

**Comment by scriptingosx** [comment]
fixed in v8, thank you!
