### ISSUE TITLE
Adobe Acrobat Reader cannot be quit for update

### ISSUE THREAD

**Issue by fleish** [Installomator/Installomator#375]
This is a follow-up from #29 

While the addition of:
`blockingProcesses=( AdobeReader )`

successfully detects a running copy of Adobe Acrobat Reader DC, attempts to use Apple Script to tell said application to quit fail because it uses the blockingProcess name:
`+checkRunningProcesses:71> runAsUser osascript -e 'tell app "AdobeReader" to quit'`

The correct application name that needs to be passed in is "Acrobat Reader":
`osascript -e 'tell app "Acrobat Reader" to quit'`

I'm not sure how to reconcile the need to detect "AdobeReader" but tell "Acrobat Reader" to be quit instead.

**Comment by Theile** [comment]
We can easily change the label blocking line to this:
```
blockingProcesses=( "Adobe Reader" )
```
But I need somebody to confirm that is the needed change.

**Comment by fleish** [comment]
I'm afraid that change won't work as it keeps the script from detecting the app is currently running. I think the process that needs to be detected is `AdobeReader` but the app name that needs to be passed to osascript is `Acrobat Reader`
