### ISSUE TITLE
Label update - Front app has an ARM version

### ISSUE THREAD

**Issue by MAJ007** [Installomator/Installomator#385]
Hi Team - please can you update the label front.sh to include logic for the ARM version of the app.

https://dl.frontapp.com/macos/Front-arm64.dmg

```
% spctl -a -vv /Volumes/Front\ 3.29.5-arm64/Front.app
/Volumes/Front 3.29.5-arm64/Front.app: accepted
source=Notarized Developer ID
origin=Developer ID Application: FrontApp. Inc. (X549L7572J)
```

**Comment by Theile** [comment]
Thank you for reporting this, I have fixed it now and added `appNewVersion` to it as well.
