### ISSUE TITLE
AnyDesk "new version" URL broken

### ISSUE THREAD

**Issue by Mac-Nerd** [Installomator/Installomator#400]
The URL in the appNewVersion line of the AnyDesk label `https://anydesk.com/da/downloads/mac-os` returns a 404. Perhaps they have removed Danish language support? 

Replacing the appNewVersion command with either of these fixes the error:
`curl -Lfs https://anydesk.com/downloads/mac-os | grep -i "d-block" | grep -E -o ">v[0-9.]* .*MB" | sed -E 's/.*v([0-9.]*) .*/\1/g'
`
`curl -fs https://anydesk.com/en/downloads/mac-os | grep -i "d-block" | grep -E -o ">v[0-9.]* .*MB" | sed -E 's/.*v([0-9.]*) .*/\1/g'
`

**Comment by Theile** [comment]
Take a look at the latest dev branch for any desk, I think we have solved this already.
