### ISSUE TITLE
merge zoom and zoomgov labels

### ISSUE THREAD

**Issue by Mac-Nerd** [Installomator/Installomator#411]
The packages installed by "zoom" and "zoomgov" are identical. 

```
% md5 zoomgov.pkg 
MD5 (zoomgov.pkg) = ec165a9501b71b446f5fe401507fe2e4
% md5 zoom.pkg   
MD5 (zoom.pkg) = ec165a9501b71b446f5fe401507fe2e4
```

**Comment by acodega** [comment]
The installer may be the same, but if your organization falls under regulations to use Zoom for Government, you'll always want to use the vendor provided URL for the gov client. It can be as simple as the zoomgov label is ensuring the CDN used falls under applicable federal regulations. (Meets certain operational restrictions, is only operational in certain countries, etc.) I don't think these labels should be merged.

**Comment by isaacatmann** [comment]
Agreed, our gov clients need to know they're using GovCloud, if in the future Zoom updates the zoomgov.pkg file and does treat it differently and we're still installing zoom.pkg for them they fall out of compliance.

**Comment by Mac-Nerd** [comment]
Ah! Excellent points. I will now stfu and figure out how to actually solve my disambiguation problem, rather than hoping it will be fixed for me.

Rats.


----

***@***.***

Charles Mangin | Head Mac Nerd | N-able

email : ***@***.******@***.***> | website : www.n-able.com<http://www.n-able.com/>

<http://www.n-able.com/>

<http://www.n-able.com/>

________________________________
