### ISSUE TITLE
Missing info new options

### ISSUE THREAD

**Issue by mvdbent** [Installomator/Installomator#414]
Missing info in the readme and/or wiki about new options. needs to be update
https://github.com/Installomator/Installomator#configuring-the-script

wiki link???

**Comment by Theile** [comment]
It's a standard wiki in github, so look at the panes and you will see it (horizontal bar almost at the top).

**Comment by scriptingosx** [comment]
I see a wiki page on the variables used in labels, but not the variables used to configure Installomator. We have most of them in the main ReadMe, but not the new ones (INTERRUPT_DND, and LOGGING are missing, as is the data dog configuration). I think this should be a wiki page of its own.

**Comment by scriptingosx** [comment]
#790
