### ISSUE TITLE
New Feature - Opening of app after being installed

### ISSUE THREAD

**Issue by piztol** [Installomator/Installomator#418]
Is it possible to modify the logic for "Re-opening of closed app" a bit, to allow it open the app after being installed, no matter if it was running or not before the installation?

**Comment by Theile** [comment]
Anything is possible!

I would say, though, that it would be out of scope for this solution. 

You could run Installomator from another script that could open the app you like, or if the app needs to be running all the time, maybe a launchd item needs to be created to keep it running.
