### ISSUE TITLE
Feature request for alternate installation method: app in dmg

### ISSUE THREAD

**Issue by fleish** [Installomator/Installomator#421]
I've been trying to find a way to automatically update the Sync app safely after the Sync team removed auto-updating from their product. Their app includes many processes, some of which cannot be "told" to quit and others that refuse to die even when their PID is killed without including the SIGKILL flag. I've tried numerous iterations and combinations within the existing Installomator options to no avail. The Sync team also insists the only way to safely update the app is by following their guide @ https://www.sync.com/help/the-sync-desktop-application/#update which currently states:

> Updating the Sync desktop app to the latest version
> 
> You can manually update Sync as follows:
> 
> 1.         [Download the latest desktop app installer](https://www.sync.com/install) to your computer. The installer will upgrade an existing installation automatically.
> 2.         On Mac open the Sync.dmg and run the Sync.app installer.
> 3.         You will be prompted to allow Sync to install software on your computer. Click Yes, Open or Run to continue.
> 4.         Sync will detect an existing installation and uninstall it first. Click Yes. Don’t worry, your existing Sync folder, files and account setting will not change.
> 5.         It will take a few seconds for the installer to configure itself, at which point you will be greeted with the Sync installer setup screen.
> 6.         The installer will detect your existing account. Ensure Reuse existing account is checked, and click Next.
> 7.         Click Finish to exit the installer.
> 
> Sync is now upgraded to the latest version.

Could a new installation method be defined to cover these types of app installs/updates? Something like `installAppInDmg` that would mount the dmg and then open the app found inside it (`Sync.app` in this case) which would then run the installation/update steps needed before exiting and being cleaned up.

**Comment by scriptingosx** [comment]
Merely opening the app would not be useful, since the app requires user interaction. If the vendor provides a command line tool to run the installation "silently" i.e. without user interaction, Installomator can use that.

**Comment by scriptingosx** [comment]
I will close this for now. If anything changes with this app's installation behavior, you can re-open a new issue and we can see if we can implement it.
