### ISSUE TITLE
Zoom version check does not match Zoom version

### ISSUE THREAD

**Issue by saess-sep** [Installomator/Installomator#433]
Context: Ran Installomator v.0.9.1 with `zoom` label.  Installed version on Mac was the latest version.

Expected: Version check would match installed version to latest version.  Zoom would not be reinstalled.

Actual: Version check found a differently formatted string (with a parenthetical) from installed app than what the source checked had (see attached log snippet).  Zoom was reinstalled.

```
2022-03-03 10:18:45 : INFO  : zoom : appversion: 5.9.6 (4993)
2022-03-03 10:18:45 : INFO  : zoom : Latest version of zoom.us is 5.9.6.4993
```

More information:  The zoomclient label has a currently commented out version checking string that works as of today on my machine if commented out.  Lines [#4541](https://github.com/Installomator/Installomator/blob/a3dbf75818bec8d2f1fdc91d490ec5cf67745308/Installomator.sh#L4541) and Line [#4554](https://github.com/Installomator/Installomator/blob/a3dbf75818bec8d2f1fdc91d490ec5cf67745308/Installomator.sh#L4554) shows the difference.

It looks like the number in the parenthetical does not change unless the third number changes.  @scriptingosx suggested only checking the first three numbers.

Full install log attached here:
[zoom-installo-log.txt](https://github.com/Installomator/Installomator/files/8179262/zoom-installo-log.txt)

**Comment by isaacatmann** [comment]
This can easily be fixed with this, I'm a little lazy on submitting a patch ;)

`        
appNewVersion=$(curl -fsIL ${downloadURL} | grep -i ^location | cut -d "/" -f5 | sed 's/\(.*\)\./\1 \(/' | sed -e 's/$/\)/')
`
