### ISSUE TITLE
Citrix Workspace version

### ISSUE THREAD

**Issue by jaakkopoyry** [Installomator/Installomator#443]
the version lookup for Citrix Workspace returned a blank value.
curl -fs https://www.citrix.com/downloads/workspace-app/mac/workspace-app-for-mac-latest.html | grep "<p>Version" | head -1 | cut -d " " -f1 | cut -d ";" -f2 | cut -d "." -f 1-3

I tweaked it as follows and was able to get the version #:
curl -fs https://www.citrix.com/downloads/workspace-app/mac/workspace-app-for-mac-latest.html | grep "<p>Version" | head -1 | cut -d ";" -f2 | cut -d "." -f 1-3 | awk '{print $2}' 
22.03.0

just fyi

**Comment by scriptingosx** [comment]
fixed in #508
