### ISSUE TITLE
update flag which stops installation if app is not present

### ISSUE THREAD

**Issue by scriptingosx** [Installomator/Installomator#449]
We have gotten a few requests on MacAdmins Slack recently for an 'update-only' mode in Installomator. That is, when the app or tool in question is _not_ present on the system, Installomator does _nothing_. If the app is present, Installomator proceeds to determine if an update exists etc. This issue is to track comments and discussion around it.

The challenge here is to determine if the app is present. This is fairly trivial for apps in dmg and other archives, since we determine the installed app to retrieve the version. However, with pkgs, this can turn out to be much harder. Since pkgs may not install a proper app bundle or install it in an arbitrary, non-standard location. Currently, we determine the installed version of a pkg from the pkg receipt. That means that if an app or tool was installed, but later removed by deleting the app, but not "forgetting" the receipt, Installomator will see that app or tool as installed, even though it was deleted.

All of that said, I believe it would make sense to use the `INSTALL` variable for this with a new, third option `update`.

**Comment by scriptingosx** [comment]
Alternative: You could create a wrapper script that checks for an app's presence and runs Installomator selectively, e.g.:

```
if [[ -d "/Applications/Firefox.app" ]]; then
    /usr/local/Installomator/Installomator.sh firefoxpkg
fi

if [[ -d "/Applications/Google Chrome.app" ]]; then
    /usr/local/Installomator/Installomator.sh googlechromepkg
fi

# repeat for each app or tool
```

**Comment by scriptingosx** [comment]
Other alternative: [Patchomator](https://github.com/Mac-Nerd/patchomator)

**Comment by Theile** [comment]
Or #410.

**Comment by scriptingosx** [comment]
discussion is happening in #410 in case you want to chime in
