### ISSUE TITLE
Put the DEBUG= variable at the top of the script

### ISSUE THREAD

**Issue by guillaumegete** [Installomator/Installomator#459]
That may sound stupid, but… we updated the script, and forgot to put back the DEBUG variable back to 0. So nothing installed as the DEBUG variable is 1 by default (and I get why).

In the new Jamf script window, the window is only 14 lines high, thus, the DEBUG variable does not appear immediately. It would help a lot if it was declared within these 14 lines, so that we don't miss its value and eventually fix it first.
<img width="1325" alt="screenshot_jamf_script_window" src="https://user-images.githubusercontent.com/59868217/160436058-ed656eda-74cf-4e67-82ca-77bd4d5fd738.png">

**Comment by scriptingosx** [comment]
I understand the frustration, but since this is bug in the Jamf Interface, that was fixed before and hopefully will be fixed again, I'd rather not change our code to adapt to that.

**Comment by guillaumegete** [comment]
Fair point ^^
