### ISSUE TITLE
macFuse

### ISSUE THREAD

**Issue by damacguy** [Installomator/Installomator#483]
The DMG for macFuse uses a shortcut at the top level to the real pkg inside the Extras folder on the DMG. It doesn't seem that Installomator is working with it...
`2022-04-12 16:54:34 : ERROR : macfuse : ERROR: couldn't find pkg in dmg FUSE for macOS.dmg`

**Comment by kryptonit1** [comment]
Can be fixed by adding ```pkgName="Install macFUSE.pkg"```. Please see label below.

```
macfuse)
    name="FUSE for macOS"
    type="pkgInDmg"
    pkgName="Install macFUSE.pkg"
    downloadURL=$(downloadURLFromGit osxfuse osxfuse)
    appNewVersion=$(versionFromGit osxfuse osxfuse)
    expectedTeamID="3T5GSNBU6W"
    ;;
```
