### ISSUE TITLE
Adobe Acrobat Reader not downloading

### ISSUE THREAD

**Issue by acodega** [Installomator/Installomator#491]
The URL methology in the `adobereaderdc` label generates a download URL which is getting an "error occurred" error page.

The generated URL is `https://ardownload.adobe.com/pub/adobe/reader/mac/AcrobatDC/2200120112/AcroRdrDC_2200120112_MUI.dmg`

If you goto the [Adobe Acrobat Reader enterprise download page](https://get.adobe.com/reader/enterprise/) the download URL ends up being `https://ardownload2.adobe.com/pub/adobe/reader/mac/AcrobatDC/2200120112/AcroRdrDC_2200120112_MUI.dmg`

We need to dig into this further to see what's happening here.

**Comment by kylejericson** [comment]
Yes please fix facing the same issue.

**Comment by tygermatt** [comment]
This is ultimately an issue on Adobe's side since their JSON is returning an invalid answer:
https://macadmins.slack.com/archives/C0653D6F9/p1649864072035669

AutoPkg uses a slightly different URL scheme to get the same underlying JSON. The issues are closed in their GitHub since it's not their problem per se, but might be useful for tracking: https://github.com/autopkg/recipes/issues/424

**Comment by acodega** [comment]
So the AR URLs work now, but Installomator's method of determining the URL is not working. It looks like the form at the `[enterprise download page](https://get.adobe.com/reader/enterprise/)` has been redesigned.

**Comment by ericbenfer** [comment]
> I changed the downloadURL method in "adobereaderdc" to use a similar method that the "adobereaderdc-update" option uses to determine the download URL and that is working for me.
> 
> adobereaderdc-update uses this: downloadURL=$(adobecurrent=`curl --fail --silent https://armmf.adobe.com/arm-manifests/mac/AcrobatDC/reader/current_version.txt | tr -d '.'` && echo [http://ardownload.adobe.com/pub/adobe/reader/mac/AcrobatDC/"$adobecurrent"/AcroRdrDCUpd"$adobecurrent"_MUI.dmg](http://ardownload.adobe.com/pub/adobe/reader/mac/AcrobatDC/%22$adobecurrent%22/AcroRdrDCUpd%22$adobecurrent%22_MUI.dmg))
> 
> Changed adobereaderdc to use this: downloadURL=$(adobecurrent=`curl --fail --silent https://armmf.adobe.com/arm-manifests/mac/AcrobatDC/reader/current_version.txt | tr -d '.'` && echo [http://ardownload.adobe.com/pub/adobe/reader/mac/AcrobatDC/"$adobecurrent"/AcroRdrDC_"$adobecurrent"_MUI.dmg](http://ardownload.adobe.com/pub/adobe/reader/mac/AcrobatDC/%22$adobecurrent%22/AcroRdrDC_%22$adobecurrent%22_MUI.dmg))

Be sure to include the "`" (ticks) around the curl command.
downloadURL=$(adobecurrent=`curl --fail --silent https://armmf.adobe.com/arm-manifests/mac/AcrobatDC/reader/current_version.txt | tr -d '.'` && echo http://ardownload.adobe.com/pub/adobe/reader/mac/AcrobatDC/"$adobecurrent"/AcroRdrDC_"$adobecurrent"_MUI.dmg)    appNewVersion=$(curl -s https://armmf.adobe.com/arm-manifests/mac/AcrobatDC/reader/current_version.txt)
