### ISSUE TITLE
AWS Workspace latest version is wrong

### ISSUE THREAD

**Issue by FletcherS7** [Installomator/Installomator#521]
Looks like the feed location has not been updated to include the update released March 3 2022.
https://docs.aws.amazon.com/workspaces/latest/userguide/amazon-workspaces-osx-client.html#osx-release-notes

**Comment by FletcherS7** [comment]
Amazon fixed this URL
It is now showing the current version again.

**Comment by KMTMark** [comment]
This has re-occurred with the latest release (v5.5) as the XML file in that URL is still showing 5.4 as latest.

**Comment by scriptingosx** [comment]
If there is no other way to get the current version, there is nothing we can do but wait for Amazon to update this. (and bug their support update it faster)
