### ISSUE TITLE
User feedback during downloading/installing would be nice

### ISSUE THREAD

**Issue by scriptingosx** [Installomator/Installomator#53]

**Comment by mkoubavs** [comment]
As an easy semi-solution to this problem, I've added additional calls to `displaynotification` to have the script notify a user when the download starts, and when the install starts, in addition to the complete notification. We found this particularly useful for large application updates such as updating Microsoft Office.

ie:
`# MARK: download the archive`
`if [[ $currentUser != "loginwindow" ]]; then
displaynotification "Downloading $name update" "Download in progress"
fi`
`# MARK: install the download`
`if [[ $currentUser != "loginwindow" ]]; then
displaynotification "Updating $name" "Update in progress. Please wait."
fi`
