### ISSUE TITLE
Inkscape not installing correctly

### ISSUE THREAD

**Issue by Gitchiel** [Installomator/Installomator#530]
I noticed, when installing Inkscape via Installomator, the app isn’t correctly installed: it always generates a crash report after quitting, prefs can’t be saved, and some other functionality isn’t working properly (esp. copy-pasting objects, when working in the app). 
I checked the prefs, and on ~/Library/Application\ Support/org.inkscape.Inkscape/ (+ subfiles/ dirs) the owner is root, instead of the logged in user.
When installing manually via drag + drop, everything’s fine - Installomator does more/less the same (so it's performed as root, and the owner changed afterwards)... The prefs aren't created on install though, instead at 1st launch, so I'd expect this difference to be irrelevant. Changing anything reg. the SYSTEMOWNER value obviously doesn't make a difference either. 
Is there a problem with the recipe? It looks ok to me, but I never created one myself yet so might be overseeing something.

Many thanks!

**Comment by scriptingosx** [comment]
Have you added an extra step to the installation that launches Inkscape from a root process?

**Comment by Gitchiel** [comment]
No, I'm using it in Jamf, as instructed here: https://scriptingosx.com/2020/06/using-installomator-with-jamf-pro/, installation via Self Service... Works fine for all other apps, must be something specific to the app or it's recipe I guess

**Comment by Gitchiel** [comment]
FYI, I created a very basic recipe (which doesn't check for the most recent version, just to test):
inkscape)
    name="Inkscape"
    type="dmg"
    downloadURL="https://media.inkscape.org/dl/resources/file/Inkscape-1.1.2.dmg"
    appNewVersion=""
    expectedTeamID="SW3D6BB6A6"
    ;;
That works without issues. I'm a bit puzzled though: the official label in Installomator does after all download the app etc. one would expect this to work as well? Unless it finds some incorrect version, of course...

**Comment by acodega** [comment]
Version 1.1.2 is an Intel only release.. I'm not sure which version was installing when you encountered the issue. There's been several releases since then, have you tested the newest release? The Installomator label is still getting the latest release correctly, except for not accounting yet for Intel vs Apple Silicon.

Right now the label will download `https://inkscape.org/gallery/item/34663/Inkscape-1.2.1_x86_64.dmg`

**Comment by Gitchiel** [comment]
Ok, took a while until I could check this; tested it today on Intel + ARM with Installomator v10.3 beta, works fine again, thanks for the info!
