### ISSUE TITLE
Update Datadog integration to allow EU Region and GDPR compliance

### ISSUE THREAD

**Issue by worthypants** [Installomator/Installomator#546]
Up to Installomator 9.2 only the non-EU data centre endpoints for datadog integration are included.
To keep EU GDPR compliance our EU logs need to be stored in an EU geo.
It would be great to have the option to select between EU/US data dog integration by a variable, and to update the endpoints to reflect the selection.

US: https://http-intake.logs.datadoghq.com/v1/input
EU: https://http-intake.logs.datadoghq.eu/api/v2/logs

Thanks a lot

**Comment by acodega** [comment]
@isaacatmann what do you think?

**Comment by scriptingosx** [comment]
@worthypants Can you test if #644 works?

**Comment by worthypants** [comment]
Hi Armin, thanks a lot . sure I am happy to  test but I’m camping for a couple of weeks.

**Comment by worthypants** [comment]
is it possible to commit this in the next release?

**Comment by scriptingosx** [comment]
I don't know. How are your tests going?

**Comment by worthypants** [comment]
I've been running with $DATADOG_INTAKE_URL set to the EU endpoints since about April.
So far without any issues. posted in PR #644.

**Comment by acodega** [comment]
We'd appreciate input from some additional testers if possible. Anyone?
