### ISSUE TITLE
[Enhancement] Alphabetize items

### ISSUE THREAD

**Issue by apizz** [Installomator/Installomator#56]
Maybe I'm OCD, but when looking through the supported install items it would be great if these were sorted alphabetically.

**Comment by Theile** [comment]
I thought the same thing, and you are right they are almost in random order, but not exactly.

Try running Installomator with now label or a wrong label, then all the labels will be returned in alphabetical order.

**Comment by scriptingosx** [comment]
the order in the code is not random, but (more or less) the order in which they were added. If at any time, we change the order of the labels in the code it will lead to _lots_ of merge conflicts afterwards, so I am reluctant to do this
