### ISSUE TITLE
Change app quitting/killing behaviour 

### ISSUE THREAD

**Issue by ThomasKaiser** [Installomator/Installomator#573]
Are you open for one or more PRs to improve/change the following behaviour?

  * unified quitting behaviour: two quit attempts are made followed by 3 attempts to kill the process nicely (SIGTERM) and if this doesn't work hard (SIGKILL), see function `QuitOrKillGently` below
  * new property `LaunchDaemonsToUnload` to unload/reload LaunchDaemons that interfere with installation, see function `DealWithLaunchDaemon` below
  * I18N/Localization
  * maybe refactor structure to call a `main` function and allow the script to be sourced for easier debugging

Current app quitting behaviour is IMO quite annoying having to wait multitudes of 30 seconds instead of _always_ quitting the most polite way possible (`quit` event, followed by `SIGTERM`, followed by `SIGKILL`). Same with constantly localizing our local Installomator copy.

    QuitOrKillGently() {
    	# function that gets called with process name as $1
    	printlog "telling app \"$1\" to quit"
    	runAsUser osascript -e "tell app \"$1\" to quit"
    	sleep 5
    	if pgrep -xq "$1"; then
    		runAsUser osascript -e "tell app \"$1\" to quit"
    		sleep 5
    	fi
    
    	# walk through all processes that can be found using pgrep and first send them a
    	# SIGTERM and after 3 seconds a SIGKILL
    	RemainingPIDs=($(pgrep "$1"))
    	Iteration=0
    	while [ ${#RemainingPIDs[@]} -gt 0 -a ${Iteration} -lt 3 ] ; do
    		for PID in ${RemainingPIDs} ; do
    			Process="$(ps ${PID} | awk -F" /" "/${PID}/ {print \"/\"\$2}")"
    			printlog "sending SIGTERM to PID ${PID}: ${Process}"
    			kill ${PID}
    		done
    		sleep 5
    		RemainingPIDs=($(pgrep "$1"))
    		for PID in ${RemainingPIDs} ; do
    			Process="$(ps ${PID} | awk -F" /" "/${PID}/ {print \"/\"\$2}")"
    			printlog "sending SIGKILL to PID ${PID}: ${Process}"
    			kill -9 ${PID}
    		done
    		sleep 3
    		RemainingPIDs=($(pgrep "$1"))
    		((Iteration++))
    	done
    } # QuitOrKillGently
    
    DealWithLaunchDaemon() {
    	# function that stops/starts launchdaemons that could otherwise interfere with install
    	# $1 is name of plist, $2 is stop/start
    
    	[ -f "$1" ] && LaunchDaemonLabel="$(defaults read "$1" Label 2>/dev/null)"
    
    	if [ "${LaunchDaemonLabel}" = "X" ]; then
    		printlog "$1 not found or not readable. Skipping"
    	else
    		case $2 in
    			stop)
    				# unload LaunchDaemon when running
    				launchctl list | grep -q "${LaunchDaemonLabel}$"
    				if [ $? -eq 0 ]; then
    					launchctl unload -w "$1" && printlog "Unloaded ${LaunchDaemonLabel}" || printlog "Unloading ${LaunchDaemonLabel} failed"
    				else
    					printlog "${LaunchDaemonLabel} not running, nothing to do"
    				fi
    				;;
    			start)
    				# load LaunchDaemon again if not already running
    				launchctl list | grep -q "${LaunchDaemonLabel}$"
    				if [ $? -ne 0 ]; then
    					launchctl load -w "$1" && printlog "Restarted ${LaunchDaemonLabel}" || printlog "Restarting ${LaunchDaemonLabel} failed"
    				else
    					printlog "${LaunchDaemonLabel} already running, nothing to do"
    				fi
    				;;
    		esac
    	fi
    } # DealWithLaunchDaemon

**Comment by ThomasKaiser** [comment]
To give an idea in which direction we're heading: https://github.com/Installomator/Installomator/compare/main...ThomasKaiser:main

**Comment by scriptingosx** [comment]
Always open for good feedback and new features. These sound very interesting.

Please file a separate PR for each feature, so that we can discuss/accept/modify/reject each individually.
