### ISSUE TITLE
sublimetext installation file

### ISSUE THREAD

**Issue by chrisshilang** [Installomator/Installomator#578]
seems sublimetext is unable to download, the link is broken.

**Comment by bbenkle** [comment]
Looks like the the Download URL has changed. 

I updated it to:

`downloadURL="$(curl -fs https://www.sublimetext.com/download_thanks?target=mac#direct-downloads | grep "mac.zip" | grep -o -i -E "https.*"| cut -d '"' -f1 | head -1)"`

**Comment by chrisshilang** [comment]
> Looks like the the Download URL has changed.
> 
> I updated it to:
> 
> `downloadURL="$(curl -fs "https://www.sublimetext.com/download_thanks?target=mac#direct-downloads" | grep "mac.zip" | grep -o -i -E "https.*"| cut -d '"' -f1 | head -1)"`

Thanks bbenkle
