### ISSUE TITLE
citrixworkspace recipe produces download error

### ISSUE THREAD

**Issue by Gitchiel** [Installomator/Installomator#587]
FYI it looks to me, like Citrix withdrew Workspace for Mac v. 22.06 since today, and because of this the current recipe doesn't seem to work anymore in Jamf. 
So some mac clients updated succesfully with Installomator 9.2 yesterday, I also downloaded 22.06 manually from Citrix.com (for PreStage purposes etc.); now I only find the previous version, 22.04 on Citrix and the Installomator recipe currently produces download errors (“URL using bad/illegal format or missing URL”). Tried some previous versions of Installomator, 9.1, 9.01, but makes no difference. Thanks in advance for hints
[Installomator.log](https://github.com/Installomator/Installomator/files/8947890/Installomator.log)

**Comment by acodega** [comment]
It seems the site has been redesigned.. they are still pointing some links to `https://www.citrix.com/downloads/workspace-app/mac/workspace-app-for-mac-latest.html` but if you browse to `https://www.citrix.com/downloads/workspace-app/mac/workspace-app-for-mac-latest1.html` then you can download 2204, and updating that URL in the label works for now too.

2206 is now showing back under the Technology Preview version too.. we may not want to update the label yet if Citrix is doing something weird with this release, but you can update the URL so your label continues installing 2204 for now. I expect we'll need to watch the website carefully for any more changes.

**Comment by acodega** [comment]
We've got reports the label works as is now, like Citrix fixed the issue and published 2206. I'll let you verify and then we can close this Issue.

**Comment by Gitchiel** [comment]
Thanks for the quick reply, the recipe is working again as expected. 

I noticed by the way, when manually downloading the "new" 22.06 installer, it's not the same file - obviously a different build (although the 22.06 from 2 days ago wasn't downloaded from the Tech Preview channel... Haven't looked deeper into this though, in our case it's not that important). 

Closing the issue...
