### ISSUE TITLE
Alfred 4 has updated to Alfred 5

### ISSUE THREAD

**Issue by tcahill-hofy** [Installomator/Installomator#630]
Alfred 4 has updated to Alfred 5, this is causing the install to fail
![Screenshot 2022-07-26 at 22 41 45](https://user-images.githubusercontent.com/100566946/181037727-b2d92771-9f4f-4c3f-9971-d1bb827e4d2d.png)
l

**Comment by bp88** [comment]
See PR #628 .

**Comment by tcahill-hofy** [comment]
Great, thank you!
