### ISSUE TITLE
SF Symbols label installs the beta version

### ISSUE THREAD

**Issue by acodega** [Installomator/Installomator#639]
The SF Symbols label is installing the beta version, currently version 4. It's likely the "latest" URL it was grepping was v3 before v4 came out in beta. This behavior can lead to unknowingly deploying the beta version when using the label.

**Comment by scriptingosx** [comment]
Maybe we can create a dedicated `sfsymbols3` for the fixed version and then `sfsymbols` points to the beta/latest? Not ideal, but fairly simple to implement

**Comment by acodega** [comment]
Maybe other way around? We'll keep the `sfsymbols` label pointed to the latest non beta version, and make a new label, `sfsymbolsbeta`. It could be useful for environments that need/want to push out the beta for designers/developers to have access to. Although there will be a period of time upon release that there isn't a beta to install.

**Comment by bartreardon** [comment]
I like that reasoning to make `sfsymbols` fetch the current non-beta release.
Quick and easy way would be to assume the "current" version will be listed last so `curl -fs "https://developer.apple.com/sf-symbols/" | grep -oe "https.*Symbols.*\.dmg" | tail -1 ` will grab that while the latest version (current or beta) will be first so `curl -fs "https://developer.apple.com/sf-symbols/" | grep -oe "https.*Symbols.*\.dmg" | head -1` can continue to get that. When there's no difference between current and latest (i.e. non-beta period) then worst case there will be only one link on the page and either label will fetch it.

**Comment by scriptingosx** [comment]
@acodega yes, you are right, that makes more sense

**Comment by Theile** [comment]
I have an idea that I might have made this label, and I totally agree! 👍

**Comment by acodega** [comment]
I think we can close this issue until the next SF Symbols beta comes out.

**Comment by sjurlohne** [comment]
I was looking into this now as I could see the label installed a beta version. Thinking I could do as @bartreardon suggested and use `head -1` to get the non beta version I can see it doesn't work out of the box. `head -1` or `tail -1` will get the same version because the beta is listed twice.

```
curl -fs "https://developer.apple.com/sf-symbols/" | grep -oe "https.*Symbols.*\.dmg"
https://devimages-cdn.apple.com/design/resources/download/SF-Symbols-6.dmg
https://devimages-cdn.apple.com/design/resources/download/SF-Symbols-5.1.dmg
https://devimages-cdn.apple.com/design/resources/download/SF-Symbols-6.dmg
```

Perhaps not pretty, but this will get the non beta version:
```
curl -fs "https://developer.apple.com/sf-symbols/" | grep devimages | grep -v beta | grep -oe "https.*Symbols.*\.dmg" | head -1
```
