### ISSUE TITLE
Error verifying Nudge PKG

### ISSUE THREAD

**Issue by wantedwriter** [Installomator/Installomator#646]
[nudge-installomator.txt](https://github.com/Installomator/Installomator/files/9329362/nudge-installomator.txt)

Latest update seems to be causing a package verification error.  Can't replicate w/ 9.2

**Comment by acodega** [comment]
The beta uses a new way to download from GitHub while avoiding API call limits, but it's got its own issues right now. In general we recommend not using the beta, and especially not with the GitHub issue being worked on. Use v9.2. You can download it via the [source code zip on the Releases page.](https://github.com/Installomator/Installomator/releases/tag/v9.2)
