### ISSUE TITLE
Merge Workspace ONE changes to branch

### ISSUE THREAD

**Issue by mwmatter** [Installomator/Installomator#648]
In the current beta release: https://github.com/Installomator/Installomator/releases/tag/v10beta1 one of the changes called out is:

"added WorkspaceOne option for LOGO (https://github.com/Installomator/Installomator/pull/517)"

After reviewing the main Installomator script I do not see the changes in the actual file. I do see the merge was committed here: https://github.com/Installomator/Installomator/commit/84d4184b1eb71237a0c4a18fc42c5462b2bde3fb but following that through I do not see the changes in the actual script.

Thanks!

**Comment by scriptingosx** [comment]
so the changes you made were made to the `Installomator.sh` in the root of the repo. (I missed this sorry) That file gets assembled from the fragments in the fragments folder. See [description of the process here](https://github.com/Installomator/Installomator/blob/main/utils/README.md).

Can you re-create the changes in the proper fragments files, in a new PR, please?

**Comment by mwmatter** [comment]
My mistake! I'm still new at all this. I created a new PR hopefully the correct way now: https://github.com/Installomator/Installomator/pull/653. Let me know if you need anything else.
