### ISSUE TITLE
Detecting new app version for Keybase label

### ISSUE THREAD

**Issue by fleish** [Installomator/Installomator#649]
Currently, the keybase label is unaware of the latest version of the software so Installomator will always download the latest version, quit the running/blocking process, compare the currently installed version against the latest version downloaded & in teh case the versions match re-start the version without having made any actual changes. I looked at adding `appNewVersion=$(versionFromGit keybase client)` to the label, but because the keybase client has a different latest version for Linux (6.0.2) vs. macOS (6.0.1) this actually makes matters worse in that Installomator now also re-installs the latest macOS version (6.0.1 currently) because it is downloaded outside of git.

Is there a way to address this so that Installomator would not pick the "latest" release from github unless that release mentioned macOS in the body as seen in the 6.0.1 release:

> "This release is for Windows, Mac OS, Android, and iOS.\r\n* On desktop\r\n  * Upgrade Electron version\r\n* On mobile\r\n  * Better scrolling to search results and links into chat\r\n  * Fix for screen freezing on backing out of chat threads\r\n  * Fix for missing images in chats\r\n  * Newer modal styling"

**Comment by acodega** [comment]
We'd need a source of information that was consistent, like a release notes page. Or perhaps if their GitHub releases were tagged `Windows`, `Linux`, `macOS`. Is there a way to use the keybase command line to print whether a new version is available? Like an `update list` function.

**Comment by fleish** [comment]
There is a local command to check for updates (`keybase update check`). I'm already running the latest version so I can't say for sure what a client needing to update will report, but it seems likely the end of the last line saying `NeedsUpdate` would switch from `flash` to `true`:

```
2022/09/01 11:38:56 DEBG Using default path to keybase: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase
2022/09/01 11:38:56 DEBG Execute: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase [version -S]
2022/09/01 11:38:56 DEBG Executed /Applications/Keybase.app/Contents/SharedSupport/bin/keybase [version -S]
2022/09/01 11:38:56 DEBG Execute: /usr/bin/sw_vers [-productVersion]
2022/09/01 11:38:56 DEBG Executed /usr/bin/sw_vers [-productVersion]
2022/09/01 11:38:56 INFO Checking for update, current version is 6.0.1-20220609162338+0fc9feea3d
2022/09/01 11:38:56 INFO Using updater source: Keybase.io
2022/09/01 11:38:56 DEBG Using options: updater.UpdateOptions{Version:"6.0.1-20220609162338+0fc9feea3d", Platform:"darwin", DestinationPath:"/Applications/Keybase.app", URL:"", Channel:"", Env:"prod", Arch:"x86_64\n", Force:false, OSVersion:"10.15.7", UpdaterVersion:"0.3.6", IgnoreSnooze:true}
2022/09/01 11:38:56 INFO Request "https://api-0.core.keybaseapi.com/_/api/1.0/pkg/update.json?arch=x86_64%0A&auto_update=1&ignore_snooze=1&install_id=262e34158a59f0b52bcddccc80c78e19e9bd2f8fa7a6fc1d&os_version=10.15.7&platform=darwin&run_mode=prod&upd_version=0.3.6&version=6.0.1-20220609162338%2B0fc9feea3d"
2022/09/01 11:38:57 DEBG Received update response: updater.Update{Version:"6.0.1-20220609162338+0fc9feea3d", Name:"v6.0.1-20220609162338+0fc9feea3d", Description:"• Various bug fixes and performance enhancements\n", InstallID:"262e34158a59f0b52bcddccc80c78e19e9bd2f8fa7a6fc1d", RequestID:"", Type:0, PublishedAt:1654791818000, Props:[]updater.Property(nil), Asset:(*updater.Asset)(0xc00012e460), NeedUpdate:false}
```

I also did some poking around and found https://prerelease.keybase.io/ that appears to show a table with links to JSON blocks that detail the latest version available by platform. `macOS` `Public` `v2` links to http://prerelease.keybase.io.s3.amazonaws.com/update-darwin-prod-v2.json - although a working, https version of that URL would be https://prerelease.keybase.io/update-darwin-prod-v2.json and contains:

```
{
  "version": "6.0.1-20220609162338+0fc9feea3d",
  "name": "v6.0.1-20220609162338+0fc9feea3d",
  "description": "• Various bug fixes and performance enhancements\n",
  "type": 0,
  "publishedAt": 1654791818000,
  "asset": {
    "name": "Keybase-6.0.1-20220609162338+0fc9feea3d.zip",
    "url": "https://s3.amazonaws.com/prerelease.keybase.io/darwin-updates/Keybase-6.0.1-20220609162338%2B0fc9feea3d.zip",
    "digest": "eda297371c83ce8f58e93be20a19ed9112e4e6755022ed709a8180bdfbd1449d",
    "signature": "BEGIN KEYBASE SALTPACK DETACHED SIGNATURE. kXR7VktZdyH7rvq v5wcIkPOwDJ1n11 M8RnkLKQGO2f3Bb fzCeMYz4S6oxLAy Cco4N255JGFZQpj ZmG1PTOSUCe7Wxh T7zWpfNEEyB58FU wWscta23TSFlZL3 5bb9n3Pxu52ezUV dkPP0Dc7N47GzUz Xrj2OCiBnAZcIeP Zxh86Rh0fkv0Cxu E. END KEYBASE SALTPACK DETACHED SIGNATURE.\n",
    "localPath": ""
  }
}
```

I think the `keybase update check` method is probably the more reliable route in case the URLs change at some point in the future.
