### ISSUE TITLE
v10beta1 Source Code - Installomator.sh Missing swiftDialog Integration

### ISSUE THREAD

**Issue by speedybutters** [Installomator/Installomator#668]
As the title suggests, when downloading the source code for v10beta1 from these links: 
[Source code (zip)](https://github.com/Installomator/Installomator/archive/refs/tags/v10beta1.zip)
[Source code (tar.gz)](https://github.com/Installomator/Installomator/archive/refs/tags/v10beta1.tar.gz)

The Installomator.sh script appears to be missing the new swiftDialog integration; for example there's no variables for `DIALOG_CMD_FILE=""` or `DIALOG_LIST_ITEM_NAME=""`.

When downloading the pkg installer from this link:
[Installomator-10.0beta1.pkg](https://github.com/Installomator/Installomator/releases/download/v10beta1/Installomator-10.0beta1.pkg)

And extracting Installomator.sh from there, it _does_ have the swiftDialog integration present, so it appears it's just the source code downloads that have a different version of the script

**Comment by scriptingosx** [comment]
Something seems to have gone wrong when creating the release. It should be fixed in the next beta. You can always assemble a new complete script from the fragments with `./assemble.sh --script`
