### ISSUE TITLE
Logitech Options+ available

### ISSUE THREAD

**Issue by virtualpatrick** [Installomator/Installomator#683]
Logitech released Logitech Options+ software for newer devices with Logitech Bolt adapter.
https://download01.logi.com/web/ftp/pub/techsupport/optionsplus/logioptionsplus_installer.zip

See website for more infos:
https://www.logitech.com/de-de/software/logi-options-plus.html

**Comment by pro4tlzz** [comment]
Download has a installer embedded 
![image](https://user-images.githubusercontent.com/22709115/194422402-386a4d85-3ffa-4198-8f57-9e5b409abfde.png)

**Comment by pro4tlzz** [comment]
--quiet for silent install

`/logioptionsplus_installer.app/Contents/MacOS/logioptionsplus_installer --quiet
`

![image](https://user-images.githubusercontent.com/22709115/194422600-cfc94dd3-4dc6-492c-96bd-53107de70c34.png)
Also has a keystroke warning that users need to accept.

I'll look into seeing if Installomator supports installing from a binary and passing arguments
