### ISSUE TITLE
Github change to releases/latest page

### ISSUE THREAD

**Issue by wakco** [Installomator/Installomator#698]
Github has buried download links a step further, so to get the page with the download link in it, you have to get the expanded_assets page first, i.e.

Instead of:
`downloadURL=https://github.com$(curl -sfL "https://github.com/$gitusername/$gitreponame/releases/latest" | tr '"' "\n" | grep -i "^/.*\/releases\/download\/.*\.$filetype" | head -1)`
It now needs to be:
`downloadURL=https://github.com$(curl -sfL "$(curl -sfL https://github.com/$gitusername/$gitreponame/releases/latest | tr '"' "\n" | grep -i "expanded_assets" | head -1)" | tr '"' "\n" | grep -i "^/.*\/releases\/download\/.*\.$filetype" | head -1)`
I haven't forked the code, because I didn't have time to find all areas that need updating.

**Comment by Theile** [comment]
Wow, this is strange. I have notised the failing as well, but not on all GitHub software, so I thought it was temporary. Thanks for this!
