### ISSUE TITLE
Google Chrome not installing latest version on Intel Macs

### ISSUE THREAD

**Issue by codymoler** [Installomator/Installomator#699]
The max version of Google Chrome being installed and patched on Intel based Macs (x86_64) is 98.0.4758.102. The issue is the same across multiple devices.

Apple Silicon (arm64) Macs are correctly installing the latest version (currently 105.5195.125 at time of writing).

**Comment by Theile** [comment]
What label are you using for Google Chrome?

Did you read the release notes for version 9.2, and use googlechromepkg?

**Comment by codymoler** [comment]
You're correct, was using the wrong label. Closing issue.
