### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by hinrichd** [Installomator/Installomator#703]
Is there an option to use Installomator behind a proxy or pass a proxy argument to use systemproxy when curling new app versions from the internet? 
Thank you

**Comment by hkystar35** [comment]
@hinrichd Just to clarify, are you needing to use a corp proxy (Zscaler install or PAC file applied to the network interface) just to escape your VPN/corp network?

And are you needing authentication, too?


I'm not sure I have a real solution, but for my company, I added some variables to the top of the installomator.sh:
```sh
proxyURL="http://mycorp.hatesusers.com/"
proxyPort="80"
proxyOptions=( --proxy "$proxyURL:$proxyPort" )
```

then did a Find and Replace:

`=(curl `
with
`=(curl ${proxyOptions} `

and it worked for me at least.

**Comment by dionparsons** [comment]
I Just added this to top of Installomator.sh. I create a Pull request for this here https://github.com/Installomator/Installomator/pull/864

# Optional Setting for Proxy to be configured
# JAMF Parameter Options 7 = Proxy Server and Parameter Options 8 = Proxy Port
# If Parameters not set then blank values are put in for HTTP and HTTPS Proxy

# Parameter 7: Proxy Server
proxyserv=${7:-""}
#
# Parameter 8: Proxy Server Port
proxyport=${8:-""}
#
export HTTP_PROXY=$proxyserv:$proxyport
export HTTPS_PROXY=$proxyserv:$proxyport
export http_proxy=$proxyserv:$proxyport
export https_proxy=$proxyserv:$proxyport

**Comment by dionparsons** [comment]
I have removed my original pull request as it needed improvement, i have  created a second pull request tackling the proxies a different method https://github.com/Installomator/Installomator/pull/870
