### ISSUE TITLE
Add ability to reopen app after update completes

### ISSUE THREAD

**Issue by apizz** [Installomator/Installomator#71]
There are two scenarios that I would like to see addressed as part of this request:

1. If the app is detected to be running and the user opts to quit & update the app, if an additional command line flag is provided (something like `--relaunch-app`) that Installomator will reopen the app (`open -a "<App Name>"`) once the app has been updated.
2. If the script is run as part of a Jamf policy, add another parameter to specify one or more flags to accommodate this and potentially other CLI options.

In the case of a recent addition - `sizeup` - the app runs in the menubar and by and large isn't really noticeable until you need to use it.  Want to save users who are doing the right thing by updating their software to not then have to manually relaunch it or realize when they try to use it that it's not running.

**Comment by scriptingosx** [comment]
this is simple enough for apps with a single process, but what about apps that have multiple processes?

**Comment by Theile** [comment]
I think we have fixed this, by opening the app if Installomator loses it. We even added BLOCKING_PROCESS_ACTION "quit" so these menu items can be simply asked to quit without requesting user interaction for that.
