### ISSUE TITLE
Req: Annotated list of labels

### ISSUE THREAD

**Issue by Mac-Nerd** [Installomator/Installomator#718]
I've started work on a human-readable expanded rundown of the existing labels. It includes a "friendly" name for what each installs, a brief "what is this?" description, any additional notes on installation or usage, and a link to the website/readme for more information.

https://github.com/Mac-Nerd/Installomator/blob/dev/fragments/labels/ReadMe.md

I need some help filling in the gaps (mostly "what is X?" for all values of X) before I can submit a PR.

**Comment by scriptingosx** [comment]
While I don't want to burden the maintainers of this repo with this task, I approve of the idea. I think it should work fine as an external, but related project.

I don't think this is the right forum to solicit help and attention, I would recommend using the `#installomator` channel on MacAdmins Slack.
