### ISSUE TITLE
MDMMosyle Installomator.sh script referenced in wiki is no longer in repo

### ISSUE THREAD

**Issue by PaperFixie** [Installomator/Installomator#737]
I am attempting to follow the wiki's guidance for setting up Installomator with Mosyle, but the script that is referenced in the wiki isn't in the MDM folder anymore. Is there a different script that we should be utilizing or was this omitted in error?

**Comment by Theile** [comment]
Your right, we need to update the wiki. 

But find my presentation from MacSysAdmin.se and you will get full instructions on the new MDM scripts.

**Comment by Theile** [comment]
You can also read the README in the folder og the MDM scripts.
