### ISSUE TITLE
include Dependancy workflow

### ISSUE THREAD

**Issue by NinjaFez** [Installomator/Installomator#743]
Hi All, 

Just started seeing if installomater can replace some of our strait forward packing work.  inkscape was one of our first attempts but knowing it requires XQuartz we made a installomater version of this to run before.  considering that this could be automated for programs that need others to work, IE. add a function/param to specify more labels to run before, or perhaps within the label definition the option to call a different label as a prereq for programs that need it?

can appreciate that most labels don't need this but though it would be a nice feature.

**Comment by scriptingosx** [comment]
There are several examples of scripts that in turn call several Installomator labels in the `MDM` folder that you should be able to adapt.
