### ISSUE TITLE
Sublime Text Won't install

### ISSUE THREAD

**Issue by Phunnyx** [Installomator/Installomator#765]
Script result: 2022-11-15 11:08:10 : REQ   :  : shifting arguments for Jamf2022-11-15 11:08:10 : REQ   : sublimetext : ################## Start Installomator v. 9.2, date 2022-05-16 2022-11-15 11:08:10 : INFO  : sublimetext : ################## Version: 9.2 2022-11-15 11:08:10 : INFO  : sublimetext : ################## Date: 2022-05-16 2022-11-15 11:08:10 : INFO  : sublimetext : ################## sublimetext 2022-11-15 11:08:11 : INFO  : sublimetext : BLOCKING_PROCESS_ACTION=tell_user 2022-11-15 11:08:11 : INFO  : sublimetext : NOTIFY=success 2022-11-15 11:08:11 : INFO  : sublimetext : LOGGING=INFO 2022-11-15 11:08:11 : INFO  : sublimetext : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns 2022-11-15 11:08:11 : INFO  : sublimetext : Label type: zip 2022-11-15 11:08:11 : INFO  : sublimetext : archiveName: Sublime Text.zip 2022-11-15 11:08:11 : INFO  : sublimetext : no blocking processes defined, using Sublime Text as default 2022-11-15 11:08:11 : INFO  : sublimetext : name: Sublime Text, appName: Sublime Text.app 2022-11-15 11:08:11.597 mdfind[4793:96780] [UserQueryParser] Loading keywords and predicates for locale "sv_SE" 2022-11-15 11:08:11.597 mdfind[4793:96780] [UserQueryParser] Loading keywords and predicates for locale "sv" 2022-11-15 11:08:11.662 mdfind[4793:96780] Couldn't determine the mapping between prefab keywords and predicates. 2022-11-15 11:08:11.662 mdfind[4793:96780] Couldn't determine the mapping between prefab keywords and predicates. 2022-11-15 11:08:11 : WARN  : sublimetext : No previous app found 2022-11-15 11:08:11 : WARN  : sublimetext : could not find Sublime Text.app 2022-11-15 11:08:11 : INFO  : sublimetext : appversion:  2022-11-15 11:08:11 : INFO  : sublimetext : Latest version of Sublime Text is Build 4143 2022-11-15 11:08:11 : REQ   : sublimetext : Downloading  to Sublime Text.zip 2022-11-15 11:08:11 : ERROR : sublimetext : error downloading  ls: Sublime Text.zip: No such file or directory 2022-11-15 11:08:11 : ERROR : sublimetext : File list:  2022-11-15 11:08:11 : ERROR : sublimetext : File type: Sublime Text.zip: cannot open `Sublime Text.zip' (No such file or directory) 2022-11-15 11:08:11 : INFO  : sublimetext : App not closed, so no reopen. 2022-11-15 11:08:11 : ERROR : sublimetext : ERROR: Error downloading  error: * Closing connection -1 curl: (3) URL using bad/illegal format or missing URL  2022-11-15 11:08:11 : REQ   : sublimetext : ################## End Installomator, exit code 2
--
Error running script: return code was 2.
[STEP 3 of 4]

**Comment by Theile** [comment]
Yes, we need version 10 out.
