### ISSUE TITLE
What happened to the notifications?

### ISSUE THREAD

**Issue by macmangr** [Installomator/Installomator#774]
When installing multiple labels with the "App normal SS.sh" script (in combination with Mosyle),  notifications are no longer displayed per label but only for the last one (2 times)

**Comment by Theile** [comment]
This script does not notify about anything. Only Installomator is doing that, and it should be told to NOTIFY=all so quite some messages for each software should appear.

The NOTIFY is one of the minor differences between this script and the others, unless I made a mistake.

**Comment by macmangr** [comment]
Hi Theile,

using the following options in the script, i thought there should be one notification per label as usual, but only one notification is shown "No Update for WhatRoute!"

LOGO="mosyleb"

item="bbedit firefoxpkg_intl jabradirect keka onscreencontrol typinator whatroute"

installomatorOptions="BLOCKING_PROCESS_ACTION=prompt_user NOTIFY=all"

**Comment by macmangr** [comment]
Can it be that the script is only written for ONE app?

Tested the script again (with the above settings) after deleting some apps (Jabra, Keka, OnScreenControl and WhatRoute). Only WhatRoute was installed and there were only the notifications for this app

**Comment by acodega** [comment]
Ah yes that's correct, it's only designed for one label. The `Installomator 1st..` [script in auto-install and SS versions](https://github.com/Installomator/Installomator/tree/main/MDM) can loop through multiple labels. It's meant for one time, initial deployment and it has a method where it checks whether it's run before so it's not meant for updates. But you can look at it to get a sense of how the looping works.
