### ISSUE TITLE
Installomator v10.0 not working

### ISSUE THREAD

**Issue by diva1970** [Installomator/Installomator#779]
Good afternoon, We use JAMF pro 10.42 to deploy installomator scripts to macs for prestage deployment. As a test, a created a policy to install zoom to a test Mac in self-service; the previous installomator, v9.2, installed perfectly, but when I switched the script to v10.0 in self-service, the installation failed. I checked the applications folder; zoom did not install. Please advise. Thanks

I have listed the results from the the JAMF log

Executing Policy Install  ZOOM - Self Service App
--
Running script Installomator version 10.0...
Script exit code: 0
Script result: 2022-11-22 13:04:10 : REQ   :  : shifting arguments for Jamf2022-11-22 13:04:10 : REQ   : zoom : ################## Start Installomator v. 10.0, date 2022-11-18 2022-11-22 13:04:10 : INFO  : zoom : ################## Version: 10.0 2022-11-22 13:04:10 : INFO  : zoom : ################## Date: 2022-11-18 2022-11-22 13:04:10 : INFO  : zoom : ################## zoom 2022-11-22 13:04:10 : DEBUG : zoom : DEBUG mode 1 enabled. 2022-11-22 13:04:10 : INFO  : zoom : SwiftDialog is not installed, clear cmd file var 2022-11-22 13:04:11 : DEBUG : zoom : name=zoom.us 2022-11-22 13:04:11 : DEBUG : zoom : appName= 2022-11-22 13:04:11 : DEBUG : zoom : type=pkg 2022-11-22 13:04:11 : DEBUG : zoom : archiveName= 2022-11-22 13:04:11 : DEBUG : zoom : downloadURL=https://zoom.us/client/latest/ZoomInstallerIT.pkg 2022-11-22 13:04:11 : DEBUG : zoom : curlOptions= 2022-11-22 13:04:11 : DEBUG : zoom : appNewVersion=5.12.8.12565 2022-11-22 13:04:11 : DEBUG : zoom : appCustomVersion function: Not defined 2022-11-22 13:04:11 : DEBUG : zoom : versionKey=CFBundleVersion 2022-11-22 13:04:11 : DEBUG : zoom : packageID= 2022-11-22 13:04:11 : DEBUG : zoom : pkgName= 2022-11-22 13:04:11 : DEBUG : zoom : choiceChangesXML= 2022-11-22 13:04:11 : DEBUG : zoom : expectedTeamID=BJ4HAAB9B3 2022-11-22 13:04:11 : DEBUG : zoom : blockingProcesses= 2022-11-22 13:04:11 : DEBUG : zoom : installerTool= 2022-11-22 13:04:11 : DEBUG : zoom : CLIInstaller= 2022-11-22 13:04:11 : DEBUG : zoom : CLIArguments= 2022-11-22 13:04:11 : DEBUG : zoom : updateTool= 2022-11-22 13:04:11 : DEBUG : zoom : updateToolArguments= 2022-11-22 13:04:11 : DEBUG : zoom : updateToolRunAsCurrentUser= 2022-11-22 13:04:11 : INFO  : zoom : BLOCKING_PROCESS_ACTION=tell_user 2022-11-22 13:04:11 : INFO  : zoom : NOTIFY=success 2022-11-22 13:04:11 : INFO  : zoom : LOGGING=DEBUG 2022-11-22 13:04:11 : INFO  : zoom : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns 2022-11-22 13:04:11 : INFO  : zoom : Label type: pkg 2022-11-22 13:04:11 : INFO  : zoom : archiveName: zoom.us.pkg 2022-11-22 13:04:11 : INFO  : zoom : no blocking processes defined, using zoom.us as default 2022-11-22 13:04:11 : DEBUG : zoom : Changing directory to /Library/Application Support/JAMF/tmp 2022-11-22 13:04:11 : INFO  : zoom : name: zoom.us, appName: zoom.us.app 2022-11-22 13:04:11 : WARN  : zoom : No previous app found 2022-11-22 13:04:11 : WARN  : zoom : could not find zoom.us.app 2022-11-22 13:04:11 : INFO  : zoom : appversion:  2022-11-22 13:04:11 : INFO  : zoom : Latest version of zoom.us is 5.12.8.12565 2022-11-22 13:04:11 : INFO  : zoom : zoom.us.pkg exists and DEBUG mode 1 enabled, skipping download 2022-11-22 13:04:11 : DEBUG : zoom : DEBUG mode 1, not checking for blocking processes 2022-11-22 13:04:11 : REQ   : zoom : Installing zoom.us 2022-11-22 13:04:11 : INFO  : zoom : Verifying: zoom.us.pkg 2022-11-22 13:04:11 : DEBUG : zoom : File list: -rw-r--r--  1 root  admin   140M Nov 22 12:53 zoom.us.pkg 2022-11-22 13:04:11 : DEBUG : zoom : File type: zoom.us.pkg: xar archive compressed TOC: 4817, SHA-1 checksum 2022-11-22 13:04:11 : DEBUG : zoom : spctlOut is zoom.us.pkg: accepted 2022-11-22 13:04:11 : DEBUG : zoom : source=Notarized Developer ID 2022-11-22 13:04:11 : DEBUG : zoom : origin=Developer ID Installer: Zoom Video Communications, Inc. (BJ4HAAB9B3) 2022-11-22 13:04:11 : INFO  : zoom : Team ID: BJ4HAAB9B3 (expected: BJ4HAAB9B3 ) 2022-11-22 13:04:11 : DEBUG : zoom : DEBUG enabled, skipping installation 2022-11-22 13:04:11 : INFO  : zoom : Finishing... 2022-11-22 13:04:14 : INFO  : zoom : name: zoom.us, appName: zoom.us.app 2022-11-22 13:04:15 : WARN  : zoom : No previous app found 2022-11-22 13:04:15 : WARN  : zoom : could not find zoom.us.app 2022-11-22 13:04:15 : REQ   : zoom : Installed zoom.us 2022-11-22 13:04:15 : INFO  : zoom : notifying 2022-11-22 13:04:15 : DEBUG : zoom : DEBUG mode 1, not reopening anything 2022-11-22 13:04:15 : REQ   : zoom : All done! 2022-11-22 13:04:15 : REQ   : zoom : ################## End Installomator, exit code 0

**Comment by acodega** [comment]
Please post a policy result from Jamf or an Installomator log when you can.

**Comment by scriptingosx** [comment]
```
 DEBUG : zoom : DEBUG mode 1, not checking for blocking processes
```

[Disable DEBUG mode](https://github.com/Installomator/Installomator#debug-mode)
