### ISSUE TITLE
Microsoft Teams won't get installed

### ISSUE THREAD

**Issue by badcom** [Installomator/Installomator#780]
I'm using [this script](https://github.com/Installomator/Installomator/blob/bc4a612e15915e55ac7a7dfc76d4843a0c3b5d7f/MDM/App-update/App%20normal%20Auto-install.sh) to install Microsoft Teams via Mosyle.

When I run the script I get the below output:
```
2022-11-23 12:20:56 [LOG-BEGIN] microsoftteams
microsoftteams succesfully installed.
2022-11-23 12:20:56 : REQ   : microsoftteams : ################## Start Installomator v. 10.0, date 2022-11-18
2022-11-23 12:20:57 : REQ   : microsoftteams : No newer version.
2022-11-23 12:20:57 : REQ   : microsoftteams : ################## End Installomator, exit code 0 
[Wed Nov 23 12:20:57 -03 2022][LOG-END]
/bin/bash: line 65:  2187 Terminated: 15          /usr/bin/caffeinate -d -i -m -u
```

Although it says "microsoftteams succesfully installed.", the app doesn't get installed.

Could that be because I recently uninstalled MS Teams and the installer if detecting something somewhere?

**Comment by scriptingosx** [comment]
when you install a pkg, it is registered in the system. You can see which pkgs are registered on the system by running `pkgutil --pkgs` in the Terminal. When you delete the Teams app, but not this pkg receipt, you haven't fully uninstalled everything. Installomator uses the pkg receipts database to determine if a pkg (and which version) has been installed before.

you can run `pkgutil --forget com.example.pkg.id` to remove the registration of the pkg and Installomator (and the installation system) will treat it as a new installation

**Comment by Theile** [comment]
And using `INSTALL=force` will install it no matter if it exists already or not.
