### ISSUE TITLE
Firefox Developer Edition Label 

### ISSUE THREAD

**Issue by albiii** [Installomator/Installomator#782]
Did not exist... so I made one...

firefox_dev)
    name="Firefox Developer Edition"
    type="dmg"
    downloadURL="https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=osx&lang=en-US"
    firefoxVersions=$(curl -fs "https://product-details.mozilla.org/1.0/firefox_versions.json")
    appNewVersion=$(getJSONValue "$firefoxVersions" "LATEST_FIREFOX_DEVEL_VERSION")
    expectedTeamID="43AQ936H96"
    blockingProcesses=( firefox )
    printlog "WARNING for ERROR: Label firefox and firefox_intl should not be used. Instead use firefoxpkg and firefoxpkg_intl as per recommendations from Firefox. It's not fully certain that the app actually gets updated here. firefoxpkg and firefoxpkg_intl will have built in updates and make sure the client is updated in the future." REQ
    ;;

**Comment by scriptingosx** [comment]
Fixed with #838 in 10.3
