### ISSUE TITLE
VLC Label not pulling most recent version

### ISSUE THREAD

**Issue by Gitchiel** [Installomator/Installomator#791]
The VLC Label (from Installomator v10.0) currently isn't pulling most recent version. It reinstalls v3.0.17, instead of v3.0.18; might have to do with the fact, v3.0.18 isn't mentioned in the xml used in the label (http://update.videolan.org/vlc/sparkle/vlc-arm64.xml - same for the Intel version, btw).
For now, I'd simply use a workaround like: 
`    if [[ $(arch) == "arm64" ]]; then
        downloadURL="https://ftp.halifax.rwth-aachen.de/videolan/vlc/3.0.18/macosx/vlc-3.0.18-arm64.dmg"
    elif [[ $(arch) == "i386" ]]; then
        downloadURL="https://ftp.halifax.rwth-aachen.de/videolan/vlc/3.0.18/macosx/vlc-3.0.18-intel64.dmg"`
Thanks for any better suggestions.

**Comment by scriptingosx** [comment]
The developers often have a delay before they update the xml files which Installomator uses to determine the new version. Unless you can provide a better, non-static, method of determining the latest version, there is not much we can do.
