### ISSUE TITLE
Google Chrome Install Issue

### ISSUE THREAD

**Issue by KUSU2** [Installomator/Installomator#792]
Getting an error on Google Chrome Installing consistently (using Jamf Policy):  See attached txt.  This is part of a provisioning set of policies and the other installomator apps install without issue.  Chrome will install fine after the fact (usually with self service).  This is causing a headache as if the download gets stuck, it sits there for several minutes.  The code for Chrome has not changed from 9.2 to 10.0 so I'm not sure why it is failing now.

[Chrome Install Log.txt](https://github.com/Installomator/Installomator/files/10127488/Chrome.Install.Log.txt)

**Comment by scriptingosx** [comment]
As the log states, the error you are getting is during the actual download. The download might fail for several reasons, which are outside of the control of the script. Most commonly it is network infrastructure (a proxy or other security feature) or local security agents that consider `curl` downloading something as suspicious.
