### ISSUE TITLE
Mosyle integration

### ISSUE THREAD

**Issue by mdmmac** [Installomator/Installomator#83]
Has anyone been successful using Installomator with Mosyle MDM ? I was thinking of copying an Installomator directory with the script in it in /Users/Shared and then invoking it with a custom command. I wonder if there is a better way. Thanks for your insights.

**Comment by Theile** [comment]
I have released a branch of Installomator that I use with Mosyle, and I added version number to many of the labels in my solution. That way I can have Mosyle run the script at certain times, and only bug the user with app-updates, if a new version is available. It works very well. Take a look here: https://github.com/Theile/Installomator

**Comment by mdmmac** [comment]
Thank you @Theile your fork is exactly what I was looking for.

**Comment by scriptingosx** [comment]
@Theile this is awesome!

I have created issues #84 and #85 to make merging your changes a part of the planning. Together with the app-version issues/PRs, we should get Installomator easier to implement with Mosyle and similar systems.

**Comment by Theile** [comment]
Super, I'm more than happy to do any contribution. 

What is currently important for Mosyle is a way for the script to check installed version before trying to install a new version. Mosyle is not easy to use for patch management, so I prefer to just let the script run automatically, like every Monday morning. Only if a new version is present, will it try to install a new version. 

I have also changed order of download and notification, as I want the user to have the least amount of troubles, so I will download and check version before I will notify the user of a new installation (I think that is more user friendly, too). 

I would love to do more!
