### ISSUE TITLE
Create installation package to install Installomator.sh locally

### ISSUE THREAD

**Issue by scriptingosx** [Installomator/Installomator#84]
Some management systems (e.g. Mostly) cannot run scripts with changeable arguments. In this case it is easier to install the Installomator script locally.

- Add a workflow (script) that builds a pkg installer which drops Installomator on the disk (location? I would suggest `/usr/local/Installomator/Installomator.sh`
- Add pkg to release resources

**Comment by Theile** [comment]
Hi Armin,

I have branched your great work to a solution with version checking, and where the admin can built a pkg for installation into /usr/local/bin. 

This is easy to integrate into Mosyle. 

If it's any help, I will maintain this branch until you can fit it all into your solution. My branch will not work well with Jamf Pro.

**Comment by mdmmac** [comment]
To install locally, without a package, I used the following script (credit : Mosyle.com)

#!/bin/bash
# Download a file on /usr/local/bin

URLDOWNLOAD="http://anysite.com/Installomator.sh";

FILENAME="$(basename $URLDOWNLOAD)";
DOWNLOADFILE="/usr/local/bin/$FILENAME";

curl -L --silent -o "$DOWNLOADFILE" "$URLDOWNLOAD";

if [ -e $DOWNLOADFILE ]; then 
  echo "$DOWNLOADFILE - Success";
else
  echo "Download failed";
fi

chmod +x /usr/local/bin/Installomator.sh

URLDOWNLOAD="http://anysite.com/InstallomatorLabels.sh";

FILENAME="$(basename $URLDOWNLOAD)";
DOWNLOADFILE="/usr/local/bin/$FILENAME";

curl -L --silent -o "$DOWNLOADFILE" "$URLDOWNLOAD";

if [ -e $DOWNLOADFILE ]; then 
  echo "$DOWNLOADFILE - Success";
else
  echo "Download failed";
fi

chmod +x /usr/local/bin/InstallomatorLabels.sh

**Comment by scriptingosx** [comment]
1. downloading and installing `Labels.txt` is not necessary
2. that Mostly recommends to download a script which will be run with root privileges using curl without _any_ validation makes my hair stand up

**Comment by scriptingosx** [comment]
A signed and notarized distribution package which will install Installomator.sh in `/usr/local/Installomator/Installomator.sh` is now available in the repo:

https://github.com/scriptingosx/Installomator/blob/dev/Installomator-0.5.pkg

Please test and let me know how this works.

**Comment by Theile** [comment]
I think the script was meant for my branch, as I separated the labels out in their own script (InstallomatorLabels.sh). My basic idea was that the script could load the labels, so the labels was easier to update, and then I actually thought about som kind of web-hosting or xml-file for these labels, but that was too many changes and would not be compatible with the format used in the case statement. So now it is just a script loaded by the main script. Maybe I should merge them again …
