### ISSUE TITLE
Main or Release branch?

### ISSUE THREAD

**Issue by erefneb** [Installomator/Installomator#850]
I want to download the raw Installomator.sh
In the read me it states "Note: The main repo is a beta version".

Should I download the script from the "release" branch?
https://raw.githubusercontent.com/Installomator/Installomator/release/Installomator.sh
or "main" branch?
https://raw.githubusercontent.com/Installomator/Installomator/main/Installomator.sh

Today they are the same. Tomorrow they _may_ be different?

**Comment by scriptingosx** [comment]
Yes, the main branch is the one with the next version that we are actively working on. It should only contain new application labels, updated application labels, and minor fixes to the code, so the `main` branch should be mostly safe. 

We reserve more significant changes to the code to the `dev` branch and there will be beta releases of those for testing.

You can also get the latest release from [the `release` branch](https://github.com/Installomator/Installomator/tree/release) or from the zip you can download from [the 'Releases' page](https://github.com/Installomator/Installomator/releases).

**Comment by scriptingosx** [comment]
more detail here https://github.com/Installomator/Installomator/wiki/Branches-and-Betas
