### ISSUE TITLE
Loom label script always downloads arm64 version of app 

### ISSUE THREAD

**Issue by kylevitale** [Installomator/Installomator#853]
Hey folks,

The loom label downloads the arm64 version of loom regardless of the hardware on the client computer. Both of the curl commands result in the arm64 version being downloaded. The i386 version is never downloaded.

**Comment by kylevitale** [comment]
This command might work, although don't judge my code. This effort can be best described as "hacking around until I got something to work".

`curl -fs https://s3-us-west-2.amazonaws.com/loom.desktop.packages/loom-inc-production/desktop-packages/latest-mac.yml | awk '/url/ && /dmg/ {print $3}' | head -2 | grep -v arm64`

**Comment by scriptingosx** [comment]
See also #847
