### ISSUE TITLE
OpenVPN Connect v3

### ISSUE THREAD

**Issue by harry-gz** [Installomator/Installomator#878]
Download seems to expect a user agent string.  Updating the label to include a user agent string worked.  Snippet:

openvpnconnectv3)
    # credit: @lotnix
    name="OpenVPN Connect"
    type="pkgInDmg"
    if [[ $(arch) == "arm64" ]]; then
        pkgName="OpenVPN_Connect_[0-9_()]*_arm64_Installer_signed.pkg"
    elif [[ $(arch) == "i386" ]]; then
        pkgName="OpenVPN_Connect_[0-9_()]*_x86_64_Installer_signed.pkg"
    fi
    downloadURL="https://openvpn.net/downloads/openvpn-connect-v3-macos.dmg"
    expectedTeamID="ACV7L3WCD8"
    curlOptions=( -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" )
    ;;

**Comment by asri-tm** [comment]
PR fix #846 merged to main branch and scheduled to be added to 10.3 release, you can also get the updated codes in the main branch.
