### ISSUE TITLE
check for root earlier when not in debug mode

### ISSUE THREAD

**Issue by SmithersJr** [Installomator/Installomator#88]
When testing a new label, I test locally in debug mode first. If everything looks good there, I test locally with debug mode off before loading it up in Jamf. If I forget to run as root, I have to wait for the whole download, verification, etc. before the error, `ERROR: not running as root, exiting`. 

It would be helpful to get that error at the beginning of the process, so I don't have to wait another 8 minutes to test. :-/

(And, also, because I'm a goober that can't remember to run it with `sudo`.) :-P

**Comment by Theile** [comment]
I love that the root check is so late, as I do a lot of testing with downloading, when not in DEBUG mode, just by running it without root access.

**Comment by acodega** [comment]
I agree with @SmithersJr here, the root check should be one of the first things the script does.

**Comment by samess-flowers** [comment]
Would moving the check forward in the process while adding an additional debug state that does everything but install things resolve this for everyone?  `DEBUG=0` and `DEBUG=1` would work the way they currently do, but a new state `DEBUG=2` (which doesn't feel properly idiomatic, but would fit the pattern) could either skip the earlier root check (the easier way to implement) or purposefully terminate where the current root check is even if the program is being run as root (which feels "cleaner" to me).
