### ISSUE TITLE
firefoxpkg_intl cannot download Swedish

### ISSUE THREAD

**Issue by Pandemicus** [Installomator/Installomator#890]
The firefoxpkg_intl  (multi-language Firefox) cannot download Swedish Firefox.

On a Swedish macOS the $userLanguage will be "sv_SE".

I think it parses the download url to "osx&lang=sv" in the curl commands after, but the correct one should be "osx&lang=sv-SE"

Log from Installomator:
2023-02-08 15:57:03 : WARN  : firefoxpkg_intl : Found language sv_SE to be used for Firefox.
   Swedish                    lang=sv-SE
2023-02-08 15:57:03 : WARN  : firefoxpkg_intl : Using language sv for download.
2023-02-08 15:57:04 : WARN  : firefoxpkg_intl : Download not found for that language. Using en-US

**Comment by asri-tm** [comment]
> The firefoxpkg_intl (multi-language Firefox) cannot download Swedish Firefox.
> 
> On a Swedish macOS the $userLanguage will be "sv_SE".
> 
> I think it parses the download url to "osx&lang=sv" in the curl commands after, but the correct one should be "osx&lang=sv-SE"
> 
> Log from Installomator: 2023-02-08 15:57:03 : WARN : firefoxpkg_intl : Found language sv_SE to be used for Firefox. Swedish lang=sv-SE 2023-02-08 15:57:03 : WARN : firefoxpkg_intl : Using language sv for download. 2023-02-08 15:57:04 : WARN : firefoxpkg_intl : Download not found for that language. Using en-US

What's the output of the following command on terminal?
`defaults read .GlobalPreferences AppleLocale | tr '_' '-'`

**Comment by Pandemicus** [comment]
On a Swedish OS and Swedish location: `sv-SE`
On an English OS and Swedish location: `en-SE`

**Comment by asri-tm** [comment]
ok so looks like "firefoxpkg_intl" label needs to be updated. It's not converting the "_" to "-" as such couldn't locate sv_SE release.

`userLanguage=$(runAsUser defaults read .GlobalPreferences AppleLocale)`
to
`userLanguage=$(runAsUser defaults read .GlobalPreferences AppleLocale | tr '_' '-')`

I can raise a PR for this fix in a bit unless anyone else beats me to it

**Comment by Pandemicus** [comment]
Thank you for your help! 

I noticed now there is a "thunderbird_intl" and that one is working correctly for Swedish if it helps.

**Comment by asri-tm** [comment]
raised #893 , this should at least fix international locales. Unfortunately if en-XX is detected, it will still default to en-US
