### ISSUE TITLE
Some Microsoft Office apps do not report complete version numbers

### ISSUE THREAD

**Issue by croaker-1** [Installomator/Installomator#897]
Currently, some Office apps (I have tested microsoftexcel, microsoftoutlook, microsoftpowerpoint, microsoftword) only report a truncated version number for appNewVersion. This started causing a problem recently because we use `IGNORE_APP_STORE_APPS=yes` on our standard update policies in Jamf (we have currently have a mix of installs but have decided to standardize on the non-App Store versions) which bypasses the updateTool...but this is only a portion of the problem. Here is what I am seeing:

For example, as of today (14 Feb 2023) using:
```
downloadURL="https://go.microsoft.com/fwlink/?linkid=525134"
appNewVersion=$(curl -fsIL "$downloadURL" | grep -i location: | grep -o "/Microsoft_.*pkg" | cut -d "_" -f 3 | cut -d "." -f 1-2)
```
`$appNewVersion` returns `16.69`
```
appversion=$(defaults read $installedAppPath/Contents/Info.plist $versionKey)
##defaults read /Applications/Microsoft\ Word.app/Contents/Info.plist CFBundleShortVersionString
```
`$appversion` returns `16.69.1` which is the currently the most recent version available

When Installomator runs, it finds that `$appNewVersion` and `$appversion` do not match, so it attempts to install the most recent version it knows about (16.69). The installer downloads but silently fails to install because a newer version (16.69.1) is already installed. An example log of what that looks like:
```
2023-02-06 10:30:09 : INFO  : microsoftword : App(s) found: /Applications/Microsoft Word.app
2023-02-06 10:30:09 : INFO  : microsoftword : found app at /Applications/Microsoft Word.app, version 16.69.1, on versionKey CFBundleShortVersionString
2023-02-06 10:30:09 : INFO  : microsoftword : appversion: 16.69.1
2023-02-06 10:30:09 : INFO  : microsoftword : Label is not of type “updateronly”, and it’s set to use force to install or ignoring app store apps, so not using updateTool.
2023-02-06 10:30:09 : INFO  : microsoftword : Latest version of Microsoft Word is 16.69
2023-02-06 10:30:09 : REQ   : microsoftword : Downloading https://go.microsoft.com/fwlink/?linkid=525134 to Microsoft Word.pkg
2023-02-06 10:31:03 : REQ   : microsoftword : no more blocking processes, continue with update
2023-02-06 10:31:03 : REQ   : microsoftword : Installing Microsoft Word
2023-02-06 10:31:03 : INFO  : microsoftword : Verifying: Microsoft Word.pkg
2023-02-06 10:31:03 : INFO  : microsoftword : Team ID: UBF8T346G9 (expected: UBF8T346G9 )
2023-02-06 10:31:03 : INFO  : microsoftword : Installing Microsoft Word.pkg to /
2023-02-06 10:31:31 : INFO  : microsoftword : Finishing...
2023-02-06 10:31:34 : INFO  : microsoftword : App(s) found: /Applications/Microsoft Word.app
2023-02-06 10:31:34 : INFO  : microsoftword : found app at /Applications/Microsoft Word.app, version 16.69.1, on versionKey CFBundleShortVersionString
2023-02-06 10:31:35 : REQ   : microsoftword : Installed Microsoft Word, version 16.69.1
2023-02-06 10:31:35 : INFO  : microsoftword : notifying
2023-02-06 10:31:35.127 Management Action[18876:786775] NSNotificationCenter connection invalid
2023-02-06 10:31:40 : INFO  : microsoftword : App not closed, so no reopen.
2023-02-06 10:31:40 : REQ   : microsoftword : All done!
```
Initially, I thought getting the full version from `$downloadURL` and comparing it to `CFBundleVersion` might be a quick fix:
```
downloadURL="https://go.microsoft.com/fwlink/?linkid=525134"
appNewVersion=$(curl -fsIL "$downloadURL" | grep -i location: | grep -o "/Microsoft_.*pkg" | cut -d "_" -f 3 | cut -d "." -f 1-3)
```
`$appNewVersion` returns `16.69.23010700`
```
versionKey="CFBundleVersion"
appversion=$(defaults read $installedAppPath/Contents/Info.plist $versionKey)
##defaults read /Applications/Microsoft\ Word.app/Contents/Info.plist CFBundleVersion
```
`$appversion` returns `16.69.23011600`

It seems some updates are released as only update packages instead of full installers...and only full installers are available from the downloadURL. So much for a quick fix.

Not wanting to be beat by Microsoft, I kept digging. I found I could pull the most recent version number and updater URL using:
`curl -s https://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409MSWD2019.xml | xmllint --format --xpath "//*/array/dict[1]" - | awk -F'<key>FullUpdaterLocation</key>' '{ print $2 }' | awk -F'</string>' '{ print $1 }' | sed 's/<string>//'`
This works and seems to be consistent across all the apps (by replacing `MSWD2019` with the desired app code)...but, just to keep things complicated, these packages can only be used to update a currently installed version so they cannot directly replace the downloadURL.

I came up with a messy way to compare the updater version with the full version and some dodgy logic to decide which package to use but I was not happy with it. I was not able find a good way to do it without rewriting significant parts of Installomator outside of the `microsoftword` label...which I wanted to avoid. Ideally, I see the logic working like this (in pseudo code):
```
GET availableFullVersion, availableUpdaterVersion
IF isInstalled THEN GET installedVersion
IF ! isInstalled || (isInstalled && INSTALL=force) || (isInstalled && isAppStore && IGNORE_APP_STORE_APPS=yes) THEN install availableFullVersion and availableUpdaterVersion if required
IF isInstalled && ! isAppStore && installedVersion < availableUpdaterVersion THEN install availableUpdaterVersion
```
Maybe I am approaching this the wrong way or simply making a mountain out of a molehill here. It could be this is a fairly isolated circumstance...looking at https://macadmins.software there don't appear to have been many update-only situations in the past but only time will tell.

Outside of this specific issue, it still makes sense to use the most accurate version numbers available especially considering the version number/build number method Microsoft has employed for versioning its apps.

**Comment by aarondavidpolley** [comment]
This is an issue still. 

Looking at Microsoft Company portal and currently getting v5.2310.5 from the download URL in Installomator:

`https://go.microsoft.com/fwlink/?linkid=869655`

The file name format is:

`CompanyPortal_5.2310.5-Installer.pkg`

This URL gives you a full installer with v5.2404.0:

`https://go.microsoft.com/fwlink/?linkid=853070`

But the format of the file is:

`CompanyPortal-Installer.pkg`

So `appNewVersion` does not have a version number in the file name to fetch

Inspired by your post, this gets the new version:

```
curl -s https://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409IMCP01.xml | xmllint --format --xpath "//*/array/dict[1]" - | awk -F'<key>Title</key>' '{ print $2 }' | awk -F'</string>' '{ print $1 }' | sed 's/<string>//' | rev | cut -d' ' -f1 | rev | tr -d "\n"
```

So conceivably, this would work:

```
microsoftcompanyportal)
    name="Company Portal"
    type="pkg"
    #downloadURL="https://go.microsoft.com/fwlink/?linkid=869655"
    downloadURL="https://go.microsoft.com/fwlink/?linkid=853070"
    #appNewVersion=$(curl -fs https://macadmins.software/latest.xml | xpath '//latest/package[id="com.microsoft.intunecompanyportal.standalone"]/cfbundleshortversionstring' 2>/dev/null | sed -E 's/<cfbundleshortversionstring>([0-9.]*)<.*/\1/')
    #appNewVersion=$(curl -fsIL "$downloadURL" | grep -i location: | grep -o "/CompanyPortal_.*pkg" | cut -d "_" -f 2 | cut -d "-" -f 1)
    appNewVersion=$(curl -s https://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409IMCP01.xml | xmllint --format --xpath "//*/array/dict[1]" - | awk -F'<key>Title</key>' '{ print $2 }' | awk -F'</string>' '{ print $1 }' | sed 's/<string>//' | rev | cut -d' ' -f1 | rev | tr -d "\n")
    expectedTeamID="UBF8T346G9"
    if [[ -x "/Library/Application Support/Microsoft/MAU2.0/Microsoft AutoUpdate.app/Contents/MacOS/msupdate" && $INSTALL != "force" && $DEBUG -eq 0 ]]; then
        printlog "Running msupdate --list"
        "/Library/Application Support/Microsoft/MAU2.0/Microsoft AutoUpdate.app/Contents/MacOS/msupdate" --list
    fi
    updateTool="/Library/Application Support/Microsoft/MAU2.0/Microsoft AutoUpdate.app/Contents/MacOS/msupdate"
    updateToolArguments=( --install --apps IMCP01 )
    ;;
```

Local tests look good running `assemble.sh` to build a new version of the script after modifying `microsoftcompanyportal.sh` with this code

**Comment by croaker-1** [comment]
Nice. I've made some more headway with this issue and some other related problems. Have a look at my pull request [#1490](https://github.com/Installomator/Installomator/pull/1490) 
Maybe it will give you some additional inspiration.
