### ISSUE TITLE
Bug in versionFromGit, not every developer follows a strict numbers and dots format.

### ISSUE THREAD

**Issue by wakco** [Installomator/Installomator#905]
I wanted to submit a label for mkuser:

```
mkuser)
    name="mkuser"
    type="pkg"
    packageID="org.freegeek.pkg.mkuser"
    downloadURL="$(downloadURLFromGit freegeek-pdx mkuser)"
    appNewVersion="$(versionFromGit freegeek-pdx mkuser)"
    expectedTeamID="YRW6NUGA63"
    ;;
```

However in testing I discovered the developer @freegeek-pdx uses hyphens "-", in the version number (Currently 2022.9.30-1), which versionFromGit filters with `sed 's/[^0-9\.]//g'`, creating an incorrect mis-match with the downloaded package.

I'd like to suggest grabbing both the unfiltered and the filtered version, then compare both with the app or package.

Just to comfirm what is going on, where Installomator is getting the version wrong:
```
2023-02-22 12:02:49 : INFO  : valuesfromarguments : found packageID org.freegeek.pkg.mkuser installed, version 	<string>2022.9.30-1</string>
2023-02-22 12:02:49 : INFO  : valuesfromarguments : appversion: 	<string>2022.9.30-1</string>
2023-02-22 12:02:49 : INFO  : valuesfromarguments : Latest version of mkuser is 2022.9.301
```

Versus, what GitHub is actually reporting (unfiltered):
```
root@gnit-uw2200578 ~ # curl -sLI "https://github.com/freegeek-pdx/mkuser/releases/latest" | grep -i "^location" | tr "/" "\n" | tail -1
2022.9.30-1
```

**Comment by asri-tm** [comment]
maybe assign a new variable in the label to fix versionFromGit and use that instead? because i don't see how else we can fix this, it's up to the developer themselves.

**Comment by wakco** [comment]
You do realise this could be flipped, because it raises the obvious question, why is the sed command there anyway?

Clearly it is there to fix the version matching for some other apps, where the git version reported doesn't actually match the app of package version reported. So if this code is to be fixed, perhaps the sed command should simply be removed and the labels for the apps that sed was added to fix, should have the sed command added to them. In the meantime I'll push the suggested label, and a suggested fix or workaround for the flaw the sed command has created in Installomator.

**Comment by asri-tm** [comment]
it is tough to control since installomator is grabbing data from various sources hence labels are used for individual apps.
so tweaks/workarounds like these are not uncommon for my installomator usage.

Sorry, i wasn't aware, you can also use [AppCustomVersion() function](an appCustomVersion() {} function can now be used in a label) if you don't wanna mess with changing AppNewVersion
