### ISSUE TITLE
Add option to only update app if running

### ISSUE THREAD

**Issue by FletcherS7** [Installomator/Installomator#936]
Currently some app developers (RingCenteral for example) launch the app after installation is completed.
I don't want the app to launch the app if its not running, so currently for these apps I update them at login and then kill them.

But I want a way to update these apps if they are already running (In which case a launch after an install is fine)

**Comment by KMTMark** [comment]
There is already an argument that can be passed to block apps re-opening after installation but I'm not sure Installomator will be able to do much in these instances unless some switches can be passed to the installer.
I've noticed similar behaviour with Cisco Webex.

**Comment by asri-tm** [comment]
feels like it's easier if you scope this in your MDM like creating a smart group in jamf to identify hosts with the app running.

A good addition will be a post-install script to installomator

**Comment by FletcherS7** [comment]
> feels like it's easier if you scope this in your MDM like creating a smart group in jamf to identify hosts with the app running.
> 
> A good addition will be a post-install script to installomator

The problem with that is, JAMF's inventory of running applications is only updated after a recon, so not great for this use case.

**Comment by asri-tm** [comment]
ah yes, that's true totally forgot about that. a post-install script definitely still required for this then

**Comment by FletcherS7** [comment]
Wondering if anyone has tried to script this.
I tried reversing the blocking process method to only run the label if blocking processes were found but I have been unsuccessfully getting it to work.
