### ISSUE TITLE
Adobe Acrobat Reader Issues Updating

### ISSUE THREAD

**Issue by natkoo** [Installomator/Installomator#944]
Hi,

When i run the command for version check (which is also done in the installomator script) it doesnt show the proper latest version.

versions=( $( curl -s https://www.adobe.com/devnet-docs/acrobatetk/tools/ReleaseNotesDC/index.html | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+"| head -n 30) )

The result i get "23.001.2006" but there should be a 3 in the end - latest version right now is 23.001.20063. And because of this its not updating Adobe Reader.

Also under adobereaderdc-update i noticed that it looks for Adobe Acrobat Reader DC.app - the app is not named that, its only named Adobe Acrobat Reader.app

Example if [[ -d "/Applications/Adobe Acrobat Reader DC.app" ]];

**Comment by dnikles** [comment]
I believe this is fixed in this PR https://github.com/Installomator/Installomator/pull/933

**Comment by isaacatmann** [comment]
The new PR will work correctly for updates, it looks like adobe doesn't display the latest full version number in https://www.adobe.com/devnet-docs/acrobatetk/tools/ReleaseNotesDC/index.html, they call it: 23.001.2006x.  So we'll probably install an earlier version which is fine, and then the update will need to apply later.  This is likely a passing issue unless adobe starts to use x more often and have different versions for macOS and Windows.
