### ISSUE TITLE
Jamf Self-Service don't install apps

### ISSUE THREAD

**Issue by Aleexiiiiiii** [Installomator/Installomator#945]
Hello,
I have a problem with Installomator in Jamf Pro, it don't install any app.
I tried the script locally and it worked perfectly but not with jamf pro.
You can find attached my config :
<img width="796" alt="image" src="https://user-images.githubusercontent.com/127441149/224130804-722aa11a-9bad-450e-a800-5ec208845d6f.png">
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/127441149/224131404-1ec31aa3-3e76-4eac-844c-f9ce8e0ad8ed.png">
By advance, thanks for help

**Comment by asri-tm** [comment]
posting the jamf policy logs of the failed run should give us enough information on what went wrong.

**Comment by Aleexiiiiiii** [comment]
It worked, I just create exactly the same policy because Jamf didn't want to execute the last one
