### ISSUE TITLE
adding keeper security

### ISSUE THREAD

**Issue by frank3427** [Installomator/Installomator#977]
I need help this does not worwk if  I add to the installomator script. Does anyone else have a working example?

keepersecurity)
name="Keeper Security"
    type="dmg"
    downloadURL="https://www.keepersecurity.com/desktop_electron/Darwin/KeeperSetup.dmg"
    expectedTeamID="UBF8T346G9"
    # Set `blockingProcesses` as appropriate for Keeper Security
    blockingProcesses=( "Keeper Security" )
    # Set `forcefulQuit` as appropriate for Keeper Security
    forcefulQuit=YES
    ;;

**Comment by frank3427** [comment]
I also have tried the following
`name="Keeper Security"
type="pkg"
packageID="com.keepersecurity.mac.KeeperDesktop"
downloadURL="https://keepersecurity.com/desktop_electron/Darwin/KeeperSetup.dmg"
expectedTeamID="23A8QH23GX"
blockingProcesses=( "Keeper" )`

**Comment by asri-tm** [comment]
the app in the dmg archive is named "Keeper Password Manager.app"
You may want to specify appName in your label to define this if you plan to keep the name as "Keeper Security"
The team ID is also wrong, check out Wiki on how to obtain this.
forcefulQuit is unrecognized variable for installomator label therefore commented

https://github.com/Installomator/Installomator/wiki/Label-Variables-Reference

```
keepersecurity)
name="Keeper Security"
appName="Keeper Password Manager.app"
type="dmg"
downloadURL="https://www.keepersecurity.com/desktop_electron/Darwin/KeeperSetup.dmg"
expectedTeamID="234QNB7GCA"
# Set blockingProcesses as appropriate for Keeper Security
blockingProcesses=( "Keeper Password Manager" )
# Set forcefulQuit as appropriate for Keeper Security
# forcefulQuit=YES
;;

**Comment by frank3427** [comment]
@asri-tm  thank you for the updated information, the installation script ran, but I was not able to find the application

**Comment by frank3427** [comment]
I can confirm that now for a little while the provided section for Keepersecurity does work
