### ISSUE TITLE
 behavior when blocking processes are found

### ISSUE THREAD

**Issue by ShtIvan** [Installomator/Installomator#987]
Hi all, currently I am facing an issue when I`m trying to use the Installomator.sh with Jamf PRO. Long story short I want to install/update applications using this value - BLOCKING_PROCESS_ACTION=prompt_user_then_kill but when  I execute the policy all works except the notifications which prompt the user to choose "Quit and Update" or "Not Now". For some reason, some apps are non-blocking for their update (Chrome, Mattermost) and there is no pop-up for the user stating that it has to be closed for an update. Please for your help (ideas/plans) to handle 'correctly'  the blocking process of apps such as Google/Mattermost.

**Comment by dnikles** [comment]
mattermost issue resolved in https://github.com/Installomator/Installomator/pull/991

**Comment by scriptingosx** [comment]
are you using the googlechromepkg label? This should take care of a running app on its own...
