### ISSUE TITLE
Cisco Webex Meetings does not have an Apple Silicon install option

### ISSUE THREAD

**Issue by rs1278** [Installomator/Installomator#994]
Can be fixed with the following code:

    if [[ $(arch) == arm64 ]]; then
    	type="pkg"
        targetDir="/Applications"
        downloadURL="https://akamaicdn.webex.com/client/Cisco_Webex_Meetings.pkg"
        #blockingProcessesMaxCPU="5"
        blockingProcesses=( Webex )
    elif [[ $(arch) == i386 ]]; then
    	type="pkgInDmg"
    	downloadURL="https://akamaicdn.webex.com/client/webexapp.dmg"
        targetDir="/Applications"
    	#blockingProcessesMaxCPU="5"
    	blockingProcesses=( Webex )
    fi

**Comment by aduffner** [comment]
Hello together, I played around with it and initially ended up with this first proposal:
```sh
webexmeetings)
    name="Cisco Webex Meetings"
    expectedTeamID="DE8Y96K9QP"
    versionKey="CFBundleShortVersionString"
    blockingProcesses=( Webex )
    appNewVersion="$(curl -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15" -fs "https://help.webex.com/en-us/article/mqkve8/Webex-App-%7C-Release-notes" | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | sort -gru | head -n 1)"
    if [[ $(arch) == arm64 ]]; then 
      type="pkg"
      downloadURL="https://akamaicdn.webex.com/client/Cisco_Webex_Meetings.pkg"
    else
      type="pkgInDmg"
      downloadURL="https://akamaicdn.webex.com/client/webexapp.dmg"
    fi
    ;;
```
The remaining problem is that today on May 29th, 2023, the Cisco's site (https://help.webex.com/en-us/article/mqkve8/Webex-App-%7C-Release-notes) still says the latest version is "43.5.0.26155" even though version 43.5.4.15 was released on May 19th, 2023.
